// ==UserScript==
// @name         OpenAI API 平台界面简体中文
// @namespace    platform.openai.com
// @version      1.1.0
// @description  翻译 OpenAI Platform API 界面为简体中文
// @homepageURL  https://github.com/SMYQH/OpenAIPlatformTranslate
// @supportURL   https://github.com/SMYQH/OpenAIPlatformTranslate/issues
// @license      AGPL-3.0
// @icon         https://chatgpt.com/favicon.ico
// @match        https://platform.openai.com/*
// @run-at       document-idle
// @grant        none
// ==/UserScript==

(function () {
  "use strict";

  // BEGIN GENERATED TRANSLATIONS
  const TEXT = Object.freeze({
    "Service tier": "服务等级",
    "Standard": "标准",
    "WebSocket mode": "WebSocket 模式",
    "Text format": "文本格式",
    "Reasoning mode": "推理模式",
    "Reasoning effort": "推理力度",
    "standard": "标准",
    "medium": "中等",
    "Verbosity": "详细程度",
    "Summary": "摘要",
    "auto": "自动",
    "none": "无",
    "low": "低",
    "high": "高",
    "xhigh": "极高",
    "max": "最大",
    "concise": "简洁",
    "detailed": "详细",
    "null": "无",
    "Beta": "测试版",
    "MCP server": "MCP 服务器",
    "MCP servers": "MCP 服务器",
    "Default speed": "默认速度",
    "Fast 1.5x speed, more usage": "Fast：1.5 倍速度，用量更高",
    "Optimize": "优化",
    "Evaluate": "评估",
    "Publish prompt": "发布 Prompt",
    "Close templates": "关闭模板",
    "Trip planner": "旅行规划助手",
    "Use the provided city information to provide a structured trip plan. Be concise and use bullet points to outline a plan for each of the days, explaining why it's interesting": "根据提供的城市信息制定结构清晰的旅行计划。简洁地列出每天的行程，并说明各项活动的特色。",
    "Image generator": "图像生成助手",
    "Search for a festival, parade, or cultural celebration happening this week anywhere in the world. Then, generate a cheerful, cartoon-style image that captures the spirit of the event: its colors, costumes, and energy. Include the name of the event and its location. After using web search, respond with just the image, nothing else": "搜索本周世界各地举办的节日、游行或文化庆典，再生成一张欢快的卡通图像，展现活动的色彩、服饰和氛围，并包含活动名称与地点。使用 Web search 后只返回图像。",
    "Code debugger": "代码调试助手",
    "You are a helpful code assistant. Read and analyze user-provided code. Identify bugs or errors, explain what’s wrong, and suggest corrected code": "阅读并分析用户提供的代码，找出错误，说明原因，并给出修正后的代码。",
    "Research assistant": "研究助手",
    "You are a research assistant. Read the user's topic and return a concise summary of recent and reliable information. Include sources when relevant.": "根据用户的研究主题，简洁总结近期可靠的信息，并在适当时提供来源。",
    "Decision helper": "决策助手",
    "Help the user make a well-reasoned decision by comparing provided options based on key criteria. Be concise and objective.": "根据关键标准比较提供的选项，帮助用户作出有依据的决策。保持简洁、客观。",
    "varName": "变量名称",
    "Edit system instructions": "编辑系统指令",
    "Generate": "生成",
    "Update the default system instructions and then save the changes.": "更新默认系统指令，然后保存修改。",
    "View code": "查看代码",
    "You can use the following code to start integrating your current prompt and settings into your application.": "使用以下代码，将当前 Prompt 和设置集成到你的应用中。",
    "Close": "关闭",
    "Your API key can be found": "你可以在",
    "here": "这里",
    ". Use environment variables or a secret-management tool to inject it into your application.": "找到 API 密钥。请通过环境变量或密钥管理工具将它传入应用。",
    "Filter MCP servers": "筛选 MCP 服务器",
    "by OpenAI": "由 OpenAI 提供",
    "Other developers": "其他开发者",
    "Server": "服务器",
    "OpenAI connectors": "OpenAI 连接器",
    "— created and maintained by OpenAI": "— 由 OpenAI 创建和维护",
    "Third party servers": "第三方服务器",
    "— created and maintained by others": "— 由第三方创建和维护",
    "Connect to MCP Server": "连接 MCP 服务器",
    "Enter server's URL and authentication details to connect": "输入服务器 URL 和认证信息以建立连接",
    "Only use MCP servers you trust and verify": "仅使用你信任且已验证的 MCP 服务器",
    "Label": "标签",
    "optional": "可选",
    "(optional)": "（可选）",
    "Description (optional)": "说明（可选）",
    "My MCP Server": "我的 MCP 服务器",
    "Authentication": "认证方式",
    "Access token / API key": "Access token / API 密钥",
    "Add your access token": "输入你的 Access token",
    "Back": "返回",
    "Connect": "连接",
    "None": "无",
    "Custom headers": "自定义请求头",
    "Attach files to file search": "为 File search 添加文件",
    "Drag your files here or click to upload": "将文件拖到这里，或点击上传",
    "Information in attached files will be available to this response.": "此响应可以使用所附文件中的信息。",
    "Upload": "上传",
    "Attach existing vector store": "关联现有 Vector Store",
    "Attach": "添加附件",
    "Configure Web Search tool": "配置 Web search 工具",
    "Configure search domains, user location, and the amount of search context.": "设置搜索网站、用户位置和搜索上下文大小。",
    "Version": "版本",
    "Web search tool version": "Web search 工具版本",
    "Latest": "最新版",
    "Deprecated": "已弃用",
    "Search only in these websites": "仅搜索这些网站",
    "e.g. en.wikipedia.org, arxiv.org": "例如：en.wikipedia.org、arxiv.org",
    "Enter domains or subdomains like \"example.com\" or \"blog.example.com\". Full paths like \"example.com/path\" are not supported.": "输入域名或子域名，例如 \"example.com\" 或 \"blog.example.com\"。不支持 \"example.com/path\" 这样的完整路径。",
    "User's location": "用户位置",
    "Country": "国家/地区",
    "Select a country...": "选择国家/地区…",
    "Region": "地区",
    "City": "城市",
    "Timezone": "时区",
    "Select a timezone...": "选择时区…",
    "Search context size": "搜索上下文大小",
    "Size": "尺寸",
    "Quality": "质量",
    "Output format": "输出格式",
    "Background": "背景",
    "Partial images": "部分图像数量",
    "Transparent": "透明",
    "Opaque": "不透明",
    "Run Python code and analyze uploaded files.": "运行 Python 代码并分析上传的文件。",
    "Adding files is optional.": "添加文件为可选操作。",
    "Select files": "选择文件",
    "Network access": "网络访问",
    "Allow or restrict outbound network access from the container.": "允许或限制容器向外部网络发起连接。",
    "Container network access": "容器网络访问",
    "Allowlist": "允许列表",
    "Hosted shell": "托管 Shell",
    "Hosted Shell": "托管 Shell",
    "Run commands in a hosted container with optional files and skills.": "在托管容器中运行命令，并可添加文件和 Skills。",
    "Add files": "添加文件",
    "Drag files here or choose from your device.": "将文件拖到这里，或从设备中选择文件。",
    "Skill input mode": "Skill 输入方式",
    "Skill IDs": "Skill ID",
    "Upload Skills": "上传 Skills",
    "Separate by space or comma. Optional.": "用空格或逗号分隔。此项可选。",
    "The model will intelligently decide to call functions based on input it receives from the user. Function definitions may include an": "模型会根据用户输入决定是否调用 Function。Function 定义可包含",
    "that describes their structured result.": "，用于描述其结构化结果。",
    "Definition": "定义",
    "Examples": "示例",
    "to ensure the model's response always follows this schema.": "，确保模型响应始终符合此 schema。",
    "Describe what your function does (or paste your code), and we'll generate a definition.": "描述 Function 的用途（或粘贴代码），以生成定义。",
    "The model will intelligently decide to call custom tools based on input it receives from the user.": "模型会根据用户输入决定是否调用自定义工具。",
    "Describe what your tool should do, e.g. execute arbitrary code.": "描述工具的用途，例如执行代码。",
    "Format": "格式",
    "Grammar (Lark syntax)": "语法（Lark）",
    "Grammar (Regex syntax)": "语法（Regex）",
    "Apply patch tool": "Apply patch 工具",
    "Allows the model to apply patches to files in your environment. Apply patch operations map directly to the": "允许模型为环境中的文件应用补丁。Apply patch 操作直接对应",
    ". Respond with whether the operation was successful.": "。请返回操作是否成功。",
    "Tool call shape": "工具调用结构",
    "Supported operations": "支持的操作",
    "– create files with V4A diffs": "– 使用 V4A diff 创建文件",
    "– apply V4A patches to existing files": "– 为现有文件应用 V4A 补丁",
    "– remove files from disk": "– 从磁盘删除文件",
    "Add tool": "添加工具",
    "Shell tool": "Shell 工具",
    "Allow the model to execute shell commands locally. Commands stream through the": "允许模型在本地执行 Shell 命令。命令通过",
    "action and return structured stdout, stderr, and exit codes.": "操作传递，并返回结构化的 stdout、stderr 和退出码。",
    "Response shape": "响应结构",
    "Local shell": "本地 Shell",
    "Local Shell": "本地 Shell",
    "Select a model...": "选择模型…",
    "Recommended Models": "推荐模型",
    "Reasoning": "推理模型",
    "Fast, up-to-date answers with clear and relevant citations from the web": "快速提供最新答案，并附上清晰、相关的网页来源引用",
    "Describe desired model behavior (tone, tool usage, response style)": "描述所需的模型行为（语气、工具用法、响应风格）",
    "User": "用户",
    "user": "用户",
    "Assistant": "助手",
    "assistant": "助手",
    "Expand": "展开",
    "Collapse": "收起",
    "Scroll to bottom": "滚动到底部",
    "Enter task specifics. Use {{template variables}} for dynamic inputs": "输入具体任务。使用 {{template variables}} 动态传入内容",
    "Enter assistant message...": "输入助手消息…",
    "1.5x speed, more usage": "1.5 倍速度，用量更高",
    "Use a persistent WebSocket connection for this chat, which may reduce latency across turns. Turn this off to use HTTP instead.": "为此聊天使用持久 WebSocket 连接，可减少多轮交互的延迟。关闭此选项以改用 HTTP。",
    "Use a persistent WebSocket connection for this chat, which may reduce latency across turns.": "为此聊天使用持久 WebSocket 连接，可减少多轮交互的延迟。",
    "Turn this off to use HTTP instead.": "关闭此选项以改用 HTTP。",
    "Add your credit card details below. This card will be saved to your account and can be removed at any time.": "请在下方输入您的信用卡信息。该卡将保存到您的账户中，您可以随时将其移除。",
    "Default project": "默认项目",
    "Search": "搜索",
    "Home": "首页",
    "Chat": "聊天",
    "Agents": "Agents",
    "Audio": "音频",
    "Images": "图像",
    "API Keys": "API 密钥",
    "Usage": "用量",
    "Logs": "日志",
    "Batches": "批处理",
    "Storage": "存储",
    "Plugins": "插件",
    "Settings": "设置",
    "More": "更多",
    "Personal": "个人",
    "Organization": "组织",
    "Platform Home Page - OpenAI API": "OpenAI API 平台首页",
    "Collapse sidebar": "收起侧边栏",
    "Audio navigation items": "音频导航项",
    "More navigation items": "更多导航项",
    "Get started": "开始使用",
    "Dismiss": "关闭",
    "1. Create an API key": "1. 创建 API 密钥",
    "2. Test models": "2. 测试模型",
    "3. Add credits": "3. 充值",
    "API request": "API 请求",
    "API requests": "API 请求",
    "API Request": "API 请求",
    "API Requests": "API 请求",
    "Developer quickstart": "开发者快速入门",
    "Make your first API request in minutes": "几分钟内发出你的第一个 API 请求",
    "Run your next API request by adding credits.": "充值后即可发起下一条 API 请求。",
    "GPT-6 Astra, Sol, and Luna": "GPT-6 Astra、Sol 和 Luna",
    "Start building with Codex": "开始使用 Codex 构建",
    "Build with OpenAI's coding agent": "使用 OpenAI coding agent 进行构建",
    "Usage summary": "用量摘要",
    "Usage duration": "用量时间范围",
    "24h": "24 小时",
    "7d": "7 天",
    "14d": "14 天",
    "30d": "30 天",
    "Total tokens": "Token 总数",
    "Responses and Chat Completions": "Responses 与 Chat Completions",
    "Prompt caching: Hit rate": "提示缓存：命中率",
    "About prompt caching hit rate": "关于提示缓存命中率",
    "Credit remaining": "剩余余额",
    "Add credits": "充值",
    "Total requests": "请求总数",
    "Recommended models": "推荐模型",
    "New": "新",
    "Navigate onboard": "导航",
    "Search for a page to navigate to.": "搜索要前往的页面。",
    "Suggested": "推荐",
    "Build": "构建",
    "Pages": "页面",
    "Quick actions": "快捷操作",
    "Resources": "资源",
    "Create API Key": "创建 API 密钥",
    "Organization Settings": "组织设置",
    "Developer docs": "开发者文档",
    "Search developer docs": "搜索开发者文档",
    "Terms & policies": "条款与政策",
    "Create batch": "创建批处理",
    "Upload file": "上传文件",
    "Create vector store": "创建 Vector Store",
    "Upload skill": "上传 Skill",
    "Create dataset": "创建数据集",
    "Create plugin": "创建插件",
    "View rate limits": "查看速率限制",
    "Manage projects": "管理项目",
    "Choose File": "选择文件",
    "Files": "文件",
    "Vector stores": "Vector Stores",
    "Skills": "Skills",
    "Responses": "Responses",
    "Agents SDK": "Agents SDK",
    "Realtime logs": "Realtime 日志",
    "Completions": "Completions",
    "Conversations": "对话",
    "ChatKit Threads": "ChatKit 线程",
    "Project Settings": "项目设置",
    "Profile Settings": "个人资料设置",
    "Theme": "主题",
    "Live": "Live",
    "Realtime": "Realtime",
    "Translate": "翻译",
    "Text to speech": "文字转语音",
    "System mode": "跟随系统",
    "Light mode": "浅色模式",
    "Dark mode": "深色模式",
    "Help": "帮助",
    "Organization settings": "组织设置",
    "Profile settings": "个人资料设置",
    "Log out": "退出登录",
    "Owned by": "所有者",
    "My Test Key": "我的测试密钥",
    "You": "你",
    "Service account": "服务账号",
    "This API key is tied to your user and can make requests against the selected project. If you are removed from the organization or project, this key will be disabled.": "此 API 密钥关联到你的用户，可用于所选项目中的请求。如果你被移出组织或项目，此密钥将失效。",
    "Optional": "可选",
    "Project": "项目",
    "Loading projects...": "正在加载项目…",
    "Create secret key": "创建密钥",
    "Permissions": "权限",
    "All": "全部",
    "Restricted": "受限",
    "Read only": "只读",
    "Payment method needed": "需要付款方式",
    "You'll need to set up billing before you can use the playground.": "使用 Playground 前，请先设置账单信息。",
    "Finish account setup": "完成账户设置",
    "Docs": "文档",
    "Download": "下载",
    "Model": "模型",
    "Output language": "输出语言",
    "Translation model": "翻译模型",
    "Input transcription model": "输入转录模型",
    "Chinese": "中文",
    "English": "英语",
    "French": "法语",
    "German": "德语",
    "Hindi": "印地语",
    "Indonesian": "印度尼西亚语",
    "Italian": "意大利语",
    "Japanese": "日语",
    "Korean": "韩语",
    "Portuguese": "葡萄牙语",
    "Russian": "俄语",
    "Spanish": "西班牙语",
    "Vietnamese": "越南语",
    "Output device": "输出设备",
    "System default": "系统默认",
    "Speaker": "扬声器",
    "Play translated audio": "播放翻译后的音频",
    "About play translated audio": "关于播放翻译后的音频",
    "About noise reduction": "关于降噪",
    "History": "历史记录",
    "Instructions": "指令",
    "Conversation behavior": "对话行为",
    "Response format": "响应格式",
    "Speed": "语速",
    "WAV": "WAV",
    "MP3": "MP3",
    "Opus": "Opus",
    "AAC": "AAC",
    "FLAC": "FLAC",
    "PCM": "PCM",
    "Generate prompt": "生成提示",
    "Templates": "模板",
    "New audio prompt": "新建音频提示",
    "Max tokens": "最大 Token 数",
    "Custom": "自定义",
    "Unlimited": "不限",
    "Uses the model maximum.": "使用模型上限。",
    "Noise reduction": "降噪",
    "Near field": "近场",
    "Far field": "远场",
    "Automatic turn detection": "自动轮次检测",
    "Normal": "正常",
    "Threshold": "阈值",
    "Prefix padding": "前缀填充",
    "ms": "毫秒",
    "Silence duration": "静音时长",
    "Idle timeout": "空闲超时",
    "Tools": "工具",
    "Functions": "Functions",
    "Start from a prompt": "从提示开始",
    "This generates both prompts in a separate Responses request, billed to the selected organization and project. Review the results before starting a call.": "系统会通过单独的 Responses 请求生成两条提示，并向所选组织和项目计费。开始通话前请先检查结果。",
    "Prompting guide": "提示编写指南",
    "Overall prompt": "总体提示",
    "Dictate prompt": "语音输入提示",
    "Up to 32,000 characters.": "最多 32,000 个字符。",
    "Dictation is transcribed by the Audio API and billed to the selected organization and project.": "语音输入由 Audio API 转录，并向所选组织和项目计费。",
    "Generate model prompts": "生成模型提示",
    "Voice model": "语音模型",
    "Voice": "语音",
    "Opening": "开场白",
    "Requests a greeting when the session starts. It may be paraphrased or interrupted. Keep it brief: the greeting request has a 500-token limit.": "会话开始时请求进行问候。问候内容可能会被改写或打断，请保持简短；问候请求上限为 500 Token。",
    "Add voice prompt": "添加语音提示",
    "Delegated model": "委派模型",
    "Type": "类型",
    "Backend type": "后端类型",
    "Add backend prompt": "添加后端提示",
    "Cache performance": "缓存性能",
    "Cache reuse across reads and writes": "读取与写入之间的缓存复用情况",
    "Hit rate (cache-read ratio)": "命中率（缓存读取比例）",
    "Cache reads per write": "每次写入对应的缓存读取次数",
    "Token volume": "Token 用量",
    "Input composition for this period": "此时间段的输入构成",
    "Cache-read tokens": "Cache-read Tokens",
    "Cache-write tokens (30 min)": "Cache-write Tokens（30 分钟）",
    "Cache-write tokens (12 hr)": "Cache-write Tokens（12 小时）",
    "Uncached tokens": "Uncached Tokens",
    "Input token composition": "输入 Token 构成",
    "Filter cache-read ratio by model": "按模型筛选缓存读取比例",
    "Filter cache-read ratio by processing tier": "按处理等级筛选缓存读取比例",
    "Filter input token composition by model": "按模型筛选输入 Token 构成",
    "Filter input token composition by processing tier": "按处理等级筛选输入 Token 构成",
    "Prompt cache diagnostics": "提示缓存诊断",
    "Filter prompt cache diagnostics by reason": "按原因筛选提示缓存诊断",
    "Filter prompt cache diagnostics by model": "按模型筛选提示缓存诊断",
    "All reasons": "所有原因",
    "1 minute unavailable for date ranges over 1 day": "日期范围超过 1 天时，无法按 1 分钟查看",
    "1 minute": "1 分钟",
    "1 hour": "1 小时",
    "1 day": "1 天",
    "Safety usage": "安全用量",
    "Spend categories": "支出类别",
    "API capabilities": "API 功能",
    "Codex Plugins": "Codex 插件",
    "Plugin usage": "插件用量",
    "Daily blocked or banned request rate": "每日被拦截或禁止的请求比例",
    "Daily blocked or banned Safety ID rate": "每日被拦截或禁止的 Safety ID 比例",
    "Harm categories": "危害类别",
    "API source": "API 来源",
    "All API sources": "所有 API 来源",
    "Direct API": "直接 API",
    "Last 7 days": "最近 7 天",
    "Last 14 days": "最近 14 天",
    "Last 30 days": "最近 30 天",
    "Week to date": "本周至今",
    "Month to date": "本月至今",
    "Refresh": "刷新",
    "Total Spend": "总支出",
    "No data": "无数据",
    "No usage data": "没有用量数据",
    "The selected date range and group doesn't have any usage data.": "所选日期范围和分组没有用量数据。",
    "October spend": "10 月支出",
    "API Source": "API 来源",
    "Line Item": "明细项",
    "Web Searches": "网页搜索",
    "File Searches": "文件搜索",
    "Moderation": "内容审核",
    "Embeddings": "嵌入",
    "Audio Speeches": "音频生成",
    "Audio Transcriptions": "音频转录",
    "Vector Stores": "Vector Stores",
    "Code Interpreter Sessions": "代码解释器会话",
    "OpenAI Hosted Containers": "OpenAI 托管容器",
    "Users": "用户",
    "Services": "服务",
    "There is no usage data for this period and group.": "此时间段和分组没有用量数据。",
    "Fast and Priority are the same processing tier. Fast requests for existing models may appear as Priority; newer models report Fast.": "Fast 和 Priority 属于同一处理等级。现有模型的 Fast 请求可能显示为 Priority；较新的模型会显示为 Fast。",
    "Group by": "分组方式",
    "1d": "1 天",
    "Total Spend No data": "总支出：无数据",
    "0 requests": "0 个请求",
    "0 input tokens": "0 个输入 Token",
    "0 images": "0 张图像",
    "Manage": "管理",
    "Export": "导出",
    "Activity data": "活动数据",
    "Cost data": "费用数据",
    "API capability": "API 功能",
    "6 selected": "已选 6 项",
    "Projects": "项目",
    "Models": "模型",
    "File format": "文件格式",
    "CSV": "CSV",
    "JSON": "JSON",
    "TSV": "TSV",
    "Start time": "开始时间",
    "End time": "结束时间",
    "Time interval": "时间间隔",
    "Daily data is exported in files with 31 day increments.": "每日数据将按每 31 天一个文件导出。",
    "Download...": "下载…",
    "Cache reads": "缓存读取",
    "Cache writes (30 min)": "缓存写入（30 分钟）",
    "Cache writes (12 hr)": "缓存写入（12 小时）",
    "Uncached": "未缓存",
    "Our most capable model, built for the hardest end-to-end work": "我们能力最强的模型，适用于最复杂的端到端任务",
    "Our high-performance model for complex tasks where time and cost matter.": "高性能模型，适用于兼顾复杂任务、响应时间与成本的场景。",
    "Our most efficient model for focused, high-volume tasks.": "高效模型，适用于目标明确且调用量大的场景。",
    "Explore in playground": "在 Playground 中试用",
    "Read the docs": "阅读文档",
    "Audio & Voice": "音频与语音",
    "Image": "图像",
    "GPT-Live and realtime audio": "GPT-Live 与 Realtime audio",
    "Create or edit images": "创建或编辑图像",
    "Build Agents": "构建 Agents",
    "Agents API": "Agents API",
    "Build durable cloud agents with a managed harness": "使用托管的 harness 构建可靠的 cloud agents",
    "Build cloud agents with a managed harness": "使用托管的 harness 构建 cloud agents。",
    "Start building": "开始构建",
    "Function calling": "Function calling",
    "Connect models to custom functions": "将模型连接到自定义函数",
    "Web search": "Web search",
    "Search the web in real-time": "实时搜索网页",
    "File search": "File search",
    "Search throughout uploaded files": "搜索已上传的文件",
    "MCP": "MCP",
    "Model Context Protocol": "Model Context Protocol",
    "Updates": "更新",
    "PROJECTS": "项目",
    "Back to project": "返回项目",
    "General": "常规",
    "API keys": "API 密钥",
    "Admin keys": "管理员密钥",
    "People": "成员",
    "Billing": "账单",
    "Limits": "限额",
    "Tunnels": "隧道",
    "Service health": "服务状态",
    "Data controls": "数据控制",
    "Security": "安全",
    "Webhooks": "Webhook",
    "Go to Billing": "前往账单",
    "Add credits Run your next API request by adding credits.": "充值 充值后即可发起下一条 API 请求。",
    "Search projects by name...": "按名称搜索项目…",
    "Geography": "地理区域",
    "Data retention": "数据保留",
    "Active": "启用中",
    "Archived": "已归档",
    "Global": "全球",
    "Modified Abuse Monitoring (Enhanced)": "修改后的滥用监测（增强版）",
    "Modified Abuse Monitoring": "修改后的滥用监测",
    "Zero Data Retention (Enhanced)": "零数据保留（增强版）",
    "Zero Data Retention": "零数据保留",
    "Standard Retention": "标准保留期限",
    "Clear": "清除",
    "Create": "创建",
    "NAME": "名称",
    "name": "名称",
    "ID": "ID",
    "id": "ID",
    "residency": "RESIDENCY",
    "Project Residency": "项目 Residency",
    "DATA RETENTION": "数据保留",
    "MEMBERS": "成员",
    "members": "成员",
    "CREATED": "创建时间",
    "created": "创建时间",
    "MONTHLY SPEND": "月度支出",
    "Monthly spend": "月度支出",
    "Create a new project": "创建新项目",
    "Projects are shared environments where teams can collaborate and share API resources. You can set custom rate limits and manage access to resources.": "项目是团队协作和共享 API 资源的工作区。你可以自定义速率限制并管理资源访问权限。",
    "Learn more.": "了解详情。",
    "Learn more": "了解详情",
    "Name": "名称",
    "Project name": "项目名称",
    "Project ID": "项目 ID",
    "Members": "成员",
    "Groups": "组",
    "Roles": "角色",
    "Webhook": "Webhook",
    "Flex": "Flex",
    "Fast": "Fast",
    "Ultrafast": "Ultrafast",
    "Save": "保存",
    "Human-friendly label for your project, shown in user interfaces and on exports": "易于识别的项目名称，会显示在界面和导出内容中",
    "Cancel": "取消",
    "New prompt": "新建 Prompt",
    "Draft": "草稿",
    "Actions": "操作",
    "Compare": "比较",
    "Code": "代码",
    "Prompt": "Prompt",
    "Add messages to prompt": "向提示中添加消息",
    "text": "文本",
    "Store logs": "存储日志",
    "Variables": "变量",
    "Add": "添加",
    "Hosted tools": "托管工具",
    "Programmatic Tool Calling Beta": "Programmatic Tool Calling Beta",
    "Programmatic Tool Calling": "Programmatic Tool Calling",
    "Execute tool calls with code in a secure hosted runtime, reducing token usage for complex workflows.": "在安全的托管运行环境中通过代码执行工具调用，减少复杂工作流的 Token 用量。",
    "Dismiss Programmatic Tool Calling": "关闭 Programmatic Tool Calling",
    "Image generation": "Image generation",
    "Tool search": "Tool Search",
    "Add a Function, Custom, or MCP tool with defer_loading set to true to enable Tool Search.": "将 defer_loading 设为 true 的 Function、Custom 或 MCP tool 添加到 Tool Search，以启用该功能。",
    "Tool search: Add a Function, Custom, or MCP tool with defer_loading set to true to enable Tool Search.": "Tool Search：将 defer_loading 设为 true 的 Function、Custom 或 MCP tool 添加到 Tool Search，以启用该功能。",
    "Code interpreter": "Code interpreter",
    "Local tools": "本地工具",
    "Function": "Function",
    "Custom tool": "自定义工具",
    "Apply patch": "应用补丁",
    "Your conversation will appear here": "你的对话将在此处显示",
    "Ask anything": "随时提问",
    "Attach file": "附加文件",
    "Run": "运行",
    "No prompts": "暂无 Prompt",
    "You can save your current configuration to create your first prompt.": "你可以保存当前配置来创建第一个 Prompt。",
    "Unsaved changes": "有未保存的更改",
    "Agent Builder": "Agent Builder",
    "Agent Builder Create a workflow Build a chat agent workflow with custom logic and tools": "Agent Builder 创建工作流 使用自定义逻辑和工具构建 chat agent 工作流",
    "Create a workflow": "创建工作流",
    "Build a chat agent workflow with custom logic and tools": "使用自定义逻辑和工具构建 chat agent 工作流",
    "Data enrichment": "数据增强",
    "Pull together data to answer user questions": "汇总数据以回答用户问题",
    "Template": "模板",
    "Planning helper": "规划助手",
    "Simple multi-turn workflow for creating work plans": "用于制定工作计划的简单多轮工作流",
    "Customer service": "客户服务",
    "Resolve customer queries with custom policies": "按照自定义规则解答客户问题",
    "Structured Data Q/A": "结构化数据问答",
    "Query databases using natural language": "使用自然语言查询数据库",
    "Document comparison": "文档比较",
    "Analyze and highlight differences across uploaded documents": "分析并突出显示已上传文档之间的差异",
    "Internal knowledge assistant": "内部知识助手",
    "Triage and answer questions from employees": "对员工问题进行分类并作答",
    "Agent Builder will be removed on November 30, 2026. For new agent projects, we recommend using the Agents SDK or ChatGPT Workspace Agents.": "Agent Builder 将于 2026 年 11 月 30 日停用。新建 Agent 项目建议使用 Agents SDK 或 ChatGPT Workspace Agents。",
    "Build voice agents with GPT-Live, it handles a spoken conversation while a backend agent looks up information, uses tools, and completes tasks.": "使用 GPT-Live 构建语音 Agent，让它处理语音对话，同时由后端 Agent 查找信息、使用工具并完成任务。",
    "GPT-Image-2.5 Flare and GPT-Image-2.5 Sunburst launched in the API with faster generation and more precise editing.": "GPT-Image-2.5 Flare 和 GPT-Image-2.5 Sunburst 已在 API 中推出，生成速度更快，编辑也更加精准。",
    "Projects - OpenAI API": "项目 - OpenAI API",
    "Edit prompt - OpenAI API": "编辑提示 - OpenAI API",
    "Agent builder - OpenAI API": "Agent Builder - OpenAI API",
    "GPT-6.1 Sol brings near-Astra intelligence to Sol pricing for cost-efficient API workloads.": "GPT-6.1 Sol 以 Sol 级别的价格提供接近 Astra 的智能，适用于高性价比的 API 工作负载。",
    "Following the release of GPT Astra, meet GPT-6 Sol for complex coding and agentic workflows, and GPT-6 Luna for efficient, high-volume tasks.": "继 GPT Astra 发布后，现推出 GPT-6 Sol，适用于复杂编码和 agentic workflows；以及 GPT-6 Luna，适用于高效、大批量任务。",
    "Build durable cloud agents with a managed Codex harness.": "借助托管的 Codex harness，构建可靠的 cloud agents。",
    "Build durable cloud agents with a managed Codex harness with the Agents API.": "使用 Agents API 和托管的 Codex harness，构建可靠的 cloud agents。",
    "GPT-Live handles a spoken conversation while a backend agent looks up information, uses tools, and completes tasks.": "GPT-Live 可处理语音对话，同时由后端 Agent 查找信息、使用工具并完成任务。",
    "GPT-Live, it handles a spoken conversation while a backend agent looks up information, uses tools, and completes tasks.": "GPT-Live 可处理语音对话，同时由后端 Agent 查找信息、使用工具并完成任务。",
    "GPT Image 2.5 Flare and GPT-Image-2.5 Sunburst launched in the API with faster generation and more precise editing.": "GPT Image 2.5 Flare 和 GPT-Image-2.5 Sunburst 已在 API 中推出，生成速度更快，编辑也更加精准。",
    "Friendly assistant": "友好助手",
    "Troubleshooting agent": "故障排查 Agent",
    "Meeting scribe": "会议记录助手",
    "Car copilot": "汽车语音助手",
    "Language tutor": "语言辅导助手",
    "Voices": "语音",
    "Search, preview, and choose a voice for the next Live session.": "搜索、试听并选择下一次 Live 会话使用的语音。",
    "Search voices": "搜索语音",
    "Filter": "筛选",
    "Natural voices": "自然语音",
    "Generated voices": "生成语音",
    "Voice filters": "语音筛选",
    "Accent": "口音",
    "Language": "语言",
    "Gender": "性别",
    "Australian influenced": "带澳大利亚口音",
    "Brazilian influenced": "带巴西口音",
    "British influenced": "带英国口音",
    "Filipino influenced": "带菲律宾口音",
    "Irish influenced": "带爱尔兰口音",
    "North American influenced": "带北美口音",
    "Southern U.S. influenced": "带美国南部口音",
    "Warm and conversational": "温暖亲切、善于交谈",
    "Clear and direct": "清晰直接",
    "Expressive and bright": "富有表现力、明快",
    "Calm and precise": "沉稳精准",
    "Grounded and measured": "平和稳健",
    "Open and upbeat": "开朗积极",
    "Animated and earnest": "生动真诚",
    "Balanced and clear": "平衡清晰",
    "Savvy and relaxed": "干练轻松",
    "Cheerful and candid": "愉快坦率",
    "Easygoing and versatile": "随和多变",
    "Bright and inquisitive": "明亮好奇",
    "Confident and optimistic": "自信乐观",
    "Composed and direct": "沉着直接",
    "Calm and affirming": "平静肯定",
    "Clear and personable": "清晰亲切",
    "Warm and easygoing": "温暖随和",
    "Steady and grounded": "稳定沉稳",
    "Male": "男声",
    "Female": "女声",
    "Realtime Playground - OpenAI API": "Realtime Playground - OpenAI API",
    "Live Playground - OpenAI API": "Live Playground - OpenAI API",
    "Audio - OpenAI API": "音频 - OpenAI API",
    "Agents - OpenAI API": "Agents - OpenAI API",
    "New agent - OpenAI API": "新建 Agent - OpenAI API",
    "Codex - OpenAI API": "Codex - OpenAI API",
    "Usage - OpenAI API": "用量 - OpenAI API",
    "Build faster with the OpenAI API in Codex": "在 Codex 中使用 OpenAI API，更快构建应用",
    "Codex is OpenAI’s coding agent for software development. Use it to scaffold new API apps, upgrade to new models or SDKs, and improve production code.": "Codex 是 OpenAI 面向软件开发的 coding agent。你可以用它搭建新的 API 应用、升级模型或 SDK，并改进生产环境代码。",
    "1. Get Codex app": "1. 获取 Codex 应用",
    "2. Install OpenAI Developers Plugin": "2. 安装 OpenAI Developers 插件",
    "Codex quickstart Learn the basics of building with Codex": "Codex 快速入门 了解使用 Codex 构建应用的基础知识",
    "Use the plugin Create a project API key for this project": "使用插件 为此项目创建项目 API 密钥",
    "Build a new app": "构建新应用",
    "Build an app with the Responses API": "使用 Responses API 构建应用",
    "Create an interactive storybook with AI-generated scenes, illustrations, and choices that shape what happens next.": "创建互动故事书，其中包含 AI 生成的场景、插图和影响后续发展的选项。",
    "Build an agent with Agents API": "使用 Agents API 构建 Agent",
    "Turn a CSV and a question into an investigation with charts, findings, and a downloadable report.": "将 CSV 文件和问题转化为调查分析，并生成图表、发现和可下载报告。",
    "Build a voice agent with gpt-live": "使用 gpt-live 构建语音 Agent",
    "Build a voice receptionist that finds available appointments and books them as you talk.": "构建语音接待员，在对话中查找可预约时间并完成预约。",
    "Improve an existing app": "改进现有应用",
    "Upgrade to the latest model": "升级到最新模型",
    "Plan a migration to the latest model family, with model and prompt recommendations based on your current model.": "规划迁移到最新模型系列，并根据当前模型提供模型和提示建议。",
    "Optimize my API implementation": "优化我的 API 实现",
    "Improve your prompts and choose model settings that balance cost, intelligence, and latency.": "改进提示并选择兼顾成本、智能水平和延迟的模型设置。",
    "Optimize my prompt cache hit rates": "优化提示缓存命中率",
    "Create a no-code-change plan to improve prompt cache reuse, latency, and cost.": "制定无需修改代码的方案，以提高提示缓存复用率并优化延迟和成本。",
    "Copy prompt": "复制提示",
    "Open in Codex": "在 Codex 中打开",
    "Preview prompt": "预览提示",
    "Environments": "环境",
    "Sessions": "会话",
    "Vault": "保险库",
    "Create agent": "创建 Agent",
    "Describe what tasks you want it to do": "描述你希望它执行的任务",
    "Get started creating an agent": "开始创建 Agent",
    "Define an agent": "定义 Agent",
    "Choose a model, instructions, and optional function tools.": "选择模型、指令和可选函数工具。",
    "Choose a runtime": "选择运行环境",
    "Use an OpenAI-hosted environment or attach your own.": "使用 OpenAI 托管环境，或连接你自己的环境。",
    "Create a session": "创建会话",
    "Start a durable agent workspace with optional initial input.": "启动持久运行的 Agent 工作区，并可提供初始输入。",
    "Exchange events": "交换事件",
    "Stream output, send more input, and return tool results.": "流式接收输出、发送更多输入并返回工具结果。",
    "Environment template": "环境模板",
    "Environment key": "环境密钥",
    "Start session": "启动会话",
    "Create agent Describe what tasks you want it to do": "创建 Agent 描述你希望它执行的任务",
    "Recommended MCP servers: GitHub, AWS (US East) SRE agent for incident response Investigate incidents using logs, runbooks, code, and deployment history.": "推荐的 MCP 服务器：GitHub、AWS（美国东部） SRE agent 用于事件响应 使用日志、操作手册、代码和部署历史调查事件。",
    "Recommended MCP servers: Notion, Google Drive, GitHub AI teammate for Slack Turn workplace conversations and files into answers, analysis, and drafts.": "推荐的 MCP 服务器：Notion、Google Drive、GitHub Slack AI 助手 将工作对话和文件整理成答案、分析和草稿。",
    "Recommended MCP servers: Amplitude (US) Data agent Investigate business questions using available datasets and warehouse access.": "推荐的 MCP 服务器：Amplitude（美国） Data agent 使用可用数据集和数据仓库访问权限调查业务问题。",
    "Recommended MCP servers: GitHub GitHub issue investigation agent Trace bug reports to their cause and propose a fix with supporting evidence.": "推荐的 MCP 服务器：GitHub GitHub issue investigation agent 追查错误报告的根因，并提出附有证据的修复方案。",
    "Bulk invoice and contract review Review document batches against supplied policies and flag discrepancies.": "批量发票与合同审查 根据提供的政策审阅一批文档并标记差异。",
    "RECOMMENDED MODELS": "推荐模型",
    "GPT-6": "GPT-6",
    "GPT-5": "GPT-5",
    "GPT-4.1": "GPT-4.1",
    "GPT-4O": "GPT-4O",
    "GPT-3.5": "GPT-3.5",
    "GPT-6.1 Sol brings near-Astra performance to Sol pricing for cost-efficient API workloads.": "GPT-6.1 Sol 以 Sol 级别的价格提供接近 Astra 的性能，适用于高性价比 API 工作负载。",
    "Built to power complex coding and agentic workflows.": "专为复杂编码和 agentic workflows 打造。",
    "A new class of intelligence for professional work": "面向专业工作的全新智能级别",
    "Frontier model for complex professional work": "面向复杂专业工作的前沿模型",
    "GPT-5.6 model that balances intelligence and cost": "兼顾智能水平和成本的 GPT-5.6 模型",
    "GPT-5.6 model optimized for cost-sensitive workloads": "针对成本敏感型工作负载优化的 GPT-5.6 模型",
    "Fastest, most cost-efficient version of GPT-5.4": "GPT-5.4 中速度最快、成本效益最高的版本",
    "Faster, cost-efficient version of GPT-5.4": "速度更快、成本效益更高的 GPT-5.4 版本",
    "Intelligence at scale for agents & professional work": "面向 Agents 与专业工作的规模化智能",
    "Fastest, most cost-efficient version of GPT-5": "GPT-5 中速度最快、成本效益最高的版本",
    "Smaller, faster version of GPT-5 for well-defined tasks": "适用于明确任务的 GPT-5 小型高速版本",
    "Smartest non-reasoning model": "能力最强的非推理模型",
    "Smaller, faster version of GPT-4.1": "更小、更快的 GPT-4.1 版本",
    "Fastest, most cost-efficient version of GPT-4.1": "GPT-4.1 中速度最快、成本效益最高的版本",
    "Smartest reasoning model for complex tasks": "适用于复杂任务的最强推理模型",
    "Smaller, faster reasoning model": "更小、更快的推理模型",
    "New agent": "新建 Agent",
    "Setup": "设置",
    "Generate agent": "生成 Agent",
    "Agent definition": "Agent 定义",
    "Text": "文本",
    "Medium": "中等",
    "Auto": "自动",
    "Subagents": "Subagents",
    "Allow subagents": "允许使用 Subagents",
    "Let this agent delegate work to subagents.": "允许此 Agent 将工作委派给 Subagents。",
    "Add Gmail MCP server": "添加 Gmail MCP 服务器",
    "Add Drive MCP server": "添加 Drive MCP 服务器",
    "Add GitHub MCP server": "添加 GitHub MCP 服务器",
    "Add Slack MCP server": "添加 Slack MCP 服务器",
    "Add MCP server": "添加 MCP 服务器",
    "View all": "查看全部",
    "Edit Web search": "编辑网页搜索",
    "Add a Function with defer_loading set to true to enable Tool search.": "将 defer_loading 设为 true 的 Function 添加到 Tool Search，以启用该功能。",
    "Built-in tools": "内置工具",
    "Programmatic tool calling": "Programmatic Tool Calling",
    "Code execution": "代码执行",
    "File access": "文件访问",
    "View images": "查看图像",
    "Save agent definition": "保存 Agent 定义",
    "Agent config": "Agent 配置",
    "Agent config language": "Agent 配置语言",
    "Copy agent config": "复制 Agent 配置",
    "Loading...": "正在加载…",
    "OpenAI Platform": "OpenAI 平台",
    "P Personal Organization": "个人 组织",
    "Clear current value": "清除当前值",
    "No usage data The selected date range and group doesn't have any usage data.": "没有用量数据。所选日期范围和分组没有用量数据。",
    "Personal $0.00 Total tokens 0": "个人 $0.00 Token 总数 0",
    "0 requests 0 input tokens": "0 个请求，0 个输入 Token",
    "0 requests 0 images": "0 个请求，0 张图像",
    "Cache reads Cache writes (30 min) Cache writes (12 hr) Uncached": "缓存读取 缓存写入（30 分钟）缓存写入（12 小时）未缓存",
    "Priority": "Priority",
    "OpenAI API": "OpenAI API",
    "Description": "说明",
    "Voice prompt": "语音提示",
    "Backend prompt": "后端提示",
    "Use this guide": "使用本指南",
    "Create project": "创建项目",
    "User transcript model": "用户转录模型",
    "Prompt caching": "提示缓存",
    "Agents sections": "Agents 区域",
    "Getting started steps": "入门步骤",
    "Dismiss getting started steps": "关闭入门步骤",
    "Agent templates": "Agent 模板",
    "SRE agent for incident response": "处理事故的 SRE Agent",
    "Investigate incidents using logs, runbooks, code, and deployment history.": "利用日志、运维手册、代码和部署历史调查事故。",
    "AI teammate for Slack": "Slack AI 协作助手",
    "Turn workplace conversations and files into answers, analysis, and drafts.": "根据工作对话和文件生成答案、分析和草稿。",
    "Data agent": "数据 Agent",
    "Investigate business questions using available datasets and warehouse access.": "利用可用数据集和数据仓库调查业务问题。",
    "GitHub issue investigation agent": "调查 GitHub Issue 的 Agent",
    "Trace bug reports to their cause and propose a fix with supporting evidence.": "追踪问题报告的根本原因，并提供有证据支持的修复建议。",
    "Bulk invoice and contract review": "批量审查发票和合同",
    "Review document batches against supplied policies and flag discrepancies.": "根据提供的规则批量审查文档，并标记不符合之处。",
    "Search environment templates": "搜索环境模板",
    "Environment views": "环境视图",
    "Environment templates": "环境模板",
    "Keys": "密钥",
    "Loading environment templates…": "正在加载环境模板…",
    "Template name": "模板名称",
    "Template ID": "模板 ID",
    "Created at": "创建时间",
    "No environment templates yet": "暂无环境模板",
    "Environment templates save packages, setup commands, and settings for your agents.": "环境模板保存 Agent 使用的软件包、初始化命令和设置。",
    "Learn more about the difference between OpenAI-hosting and self-hosting your agents": "了解 OpenAI 托管与自行托管 Agent 的区别",
    "OpenAI-hosted": "OpenAI 托管",
    "Run your agent in an environment managed by OpenAI.": "在 OpenAI 管理的环境中运行 Agent。",
    "Self-hosted": "自行托管",
    "Connect an environment that you host and manage.": "连接你自行托管和管理的环境。",
    "Next": "下一步",
    "Create environment template": "创建环境模板",
    "These are used each time you create an instance of an environment for your agent to run in.": "每次创建供 Agent 运行的环境实例时，都会使用这些配置。",
    "My environment": "我的环境",
    "Enabled": "已启用",
    "Disabled": "已禁用",
    "Packages": "软件包",
    "See what’s included by default": "查看默认包含的内容",
    "Add package": "添加软件包",
    "Setup commands": "初始化命令",
    "Add setup command": "添加初始化命令",
    "Environment variables": "环境变量",
    "Add environment variable": "添加环境变量",
    "Search environment keys": "搜索环境密钥",
    "Add filter": "添加筛选条件",
    "Loading environment keys…": "正在加载环境密钥…",
    "Environment keys": "环境密钥",
    "Environment keys are only required for self-hosting": "仅自行托管环境需要环境密钥",
    "Status": "状态",
    "Tracking ID": "追踪 ID",
    "Secret Key": "密钥",
    "Created": "创建时间",
    "Last used": "上次使用时间",
    "Created by": "创建者",
    "No environment keys yet": "暂无环境密钥",
    "Environment keys connect your self-hosted environments to your agents.": "环境密钥将自行托管的环境连接到 Agent。",
    "Search sessions": "搜索会话",
    "Agent sessions": "Agent 会话",
    "Session ID": "会话 ID",
    "Agent name": "Agent 名称",
    "Session status": "会话状态",
    "Environment status": "环境状态",
    "Started": "启动时间",
    "Last activity": "上次活动时间",
    "Tokens": "Token 数",
    "No sessions yet": "暂无会话",
    "Start a session to begin testing your agent": "启动会话以测试 Agent",
    "Choose an agent and an environment to begin a session.": "选择 Agent 和环境以开始会话。",
    "Select an agent": "选择 Agent",
    "No agent definitions yet. Create an agent definition first.": "暂无 Agent 定义。请先创建 Agent 定义。",
    "Select an environment template": "选择环境模板",
    "No environment templates yet. Create an environment template first.": "暂无环境模板。请先创建环境模板。",
    "API secrets (optional)": "API 密钥（可选）",
    "API secrets": "API 密钥",
    "Loading secrets…": "正在加载密钥…",
    "Choose secrets for API requests from this agent’s OpenAI-hosted sandbox. Only selected secrets will be attached.": "为此 Agent 的 OpenAI 托管沙箱发出的 API 请求选择密钥。仅会附加选中的密钥。",
    "Search vault secrets": "搜索保险库密钥",
    "Vault secrets": "保险库密钥",
    "Securely store credentials your agents use to connect to external services.": "安全存储 Agent 连接外部服务所使用的凭据。",
    "Learn how secrets work": "了解密钥的使用方式",
    "Secret": "密钥",
    "Configured for": "使用方式",
    "Destination": "目标地址",
    "Vault ID": "保险库 ID",
    "No secrets yet. Create a secret and choose where it can be used.": "暂无密钥。创建密钥并选择允许使用的位置。",
    "Create secret": "创建密钥",
    "Create vault secret": "创建保险库密钥",
    "Step 1 of 2": "第 1 步，共 2 步",
    "Name your secret and enter its value. Next, choose where it can be used.": "为密钥命名并输入其值，然后选择允许使用的位置。",
    "Secret name": "密钥名称",
    "Production API key": "生产环境 API 密钥",
    "Secret value": "密钥值",
    "Enter your secret": "输入密钥",
    "The value cannot be viewed after saving. You can replace it later.": "保存后无法查看密钥值，之后可以替换。",
    "Build in Codex": "在 Codex 中构建",
    "New agent sections": "新建 Agent 区域",
    "Live view": "Live 视图",
    "Live configuration": "Live 配置",
    "Start with a single prompt to define your agent, how it should speak, and what it should do, or edit the model prompts separately…": "先用一条提示定义 Agent、说话方式和任务，或分别编辑模型提示…",
    "Optional first words": "可选的开场白",
    "Voice prompt帮助": "语音提示帮助",
    "Backend prompt帮助": "后端提示帮助",
    "Voice prompt help": "语音提示帮助",
    "Backend prompt help": "后端提示帮助",
    "Research guide": "研究指南",
    "A concise live research assistant.": "简洁的 Live 研究助手。",
    "Remove voice prompt": "移除语音提示",
    "Remove backend prompt": "移除后端提示",
    "Remove": "移除",
    "Describe how the agent should speak and behave…": "描述 Agent 的说话方式和行为…",
    "Identity, speaking style, conversational behavior, and when to delegate. Leave blank to use the default.": "设置身份、说话风格、对话行为和委派时机。留空则使用默认设置。",
    "Add instructions for the backend model…": "为后端模型添加指令…",
    "Task instructions, rules, workflows, and required authorization or confirmations for Responses.": "设置任务指令、规则、工作流程，以及 Responses 所需的授权或确认。",
    "Chat with the user as an expert agent...": "以专家 Agent 的身份与用户对话…",
    "Max tokens mode": "最大 Token 数模式",
    "Semantic": "语义检测",
    "Speak in an emotive and friendly tone...": "使用富有感情且友好的语气说话…",
    "30-day history": "最近 30 天的历史记录",
    "Close panel": "关闭面板",
    "Close history panel": "关闭历史记录面板",
    "Your history will appear here": "历史记录将在此处显示",
    "View and restore generations from the last 30 days": "查看并恢复最近 30 天生成的内容",
    "Codex quickstart": "Codex 快速入门",
    "Learn the basics of building with Codex": "了解使用 Codex 构建应用的基础知识",
    "Use the plugin": "使用插件",
    "Create a project API key for this project": "为此项目创建项目 API 密钥",
    "Hide prompt": "隐藏提示",
    "API key security guidance": "API 密钥安全指南",
    "API Key Usage": "API 密钥用量",
    "Search API keys": "搜索 API 密钥",
    "Never": "永不",
    "Revoked": "已撤销",
    "Inherited": "继承权限",
    "Create new secret key": "创建新的密钥",
    "API key owner": "API 密钥所有者",
    "List models": "列出模型",
    "Model capabilities": "模型能力",
    "Project safety alerts": "项目安全提醒",
    "Safety": "安全",
    "Export type": "导出类型",
    "Input tokens": "输入 Token 数",
    "Input uncached tokens": "未缓存的输入 Token 数",
    "Input cached tokens": "已缓存的输入 Token 数",
    "Input audio tokens": "输入音频 Token 数",
    "Output tokens": "输出 Token 数",
    "Output audio tokens": "输出音频 Token 数",
    "Model requests": "模型请求数",
    "Filter by": "筛选条件",
    "1m": "1 分钟",
    "1h": "1 小时",
    "Log source": "日志来源",
    "Search logs": "搜索日志",
    "Your Responses will appear here": "Responses 将在此处显示",
    "Use the Responses API to view your logs.": "使用 Responses API 查看日志。",
    "Date": "日期",
    "Metadata": "元数据",
    "Tool": "工具",
    "Your Agent Traces will appear here": "Agent 追踪记录将在此处显示",
    "Use the Agents SDK to collect traces.": "使用 Agents SDK 收集追踪记录。",
    "Your Realtime sessions will appear here": "Realtime 会话将在此处显示",
    "Saved Realtime session traces are shown here.": "已保存的 Realtime 会话追踪记录将在此处显示。",
    "Enable API call logging": "启用 API 调用日志",
    "Use Chat Completions to observe and evaluate your models.": "使用 Chat Completions 观察和评估模型。",
    "Enable": "启用",
    "Newest": "最新优先",
    "Oldest": "最早优先",
    "Your Conversations will appear here": "对话将在此处显示",
    "Use the Responses API with Conversations.": "通过 Conversations 使用 Responses API。",
    "Your ChatKit Threads will appear here": "ChatKit 线程将在此处显示",
    "Use ChatKit to build rich conversational experiences.": "使用 ChatKit 构建丰富的对话体验。",
    "No batches found": "未找到批处理任务",
    "Create a batch below or using the OpenAI API.": "在下方或通过 OpenAI API 创建批处理任务。",
    "Select a batch to view details.": "选择批处理任务以查看详情。",
    "Create a batch": "创建批处理任务",
    "Input file": "输入文件",
    "Add a jsonl file of request inputs for the batch.": "添加包含批处理请求输入的 jsonl 文件。",
    "Choose a file selection mode": "选择文件来源",
    "Upload new": "上传新文件",
    "Select existing": "选择现有文件",
    "Upload a file or drag your file here": "上传文件或将文件拖到这里",
    "Completion window": "完成时限",
    "The time frame within which the batch should be processed.": "批处理任务应完成处理的时间范围。",
    "Endpoint": "端点",
    "The endpoint to be used for all requests in the batch.": "批处理中所有请求使用的端点。",
    "Output Expiration": "输出到期时间",
    "Time until output/error files expire. Note: this is different from the batch completion window.": "输出或错误文件的有效期。注意：此设置与批处理完成时限不同。",
    "Select expiration option": "选择有效期选项",
    "Learn about the Batch API": "了解 Batch API",
    "Browse files": "浏览文件",
    "File ID": "文件 ID",
    "Select time unit": "选择时间单位",
    "hours": "小时",
    "days": "天",
    "Store view": "存储视图",
    "Search files by name...": "按名称搜索文件…",
    "No files found": "未找到文件",
    "Files uploaded with OpenAI API will appear here.": "通过 OpenAI API 上传的文件将在此处显示。",
    "Select a file to view details.": "选择文件以查看详情。",
    "Upload a File": "上传文件",
    "The name of the uploaded file": "上传文件的名称",
    "Purpose": "用途",
    "The purpose of the uploaded file": "上传文件的用途",
    "Time until the file expires": "文件有效期",
    "Learn about file purposes": "了解文件用途",
    "Search vector stores...": "搜索 Vector Store…",
    "Select a vector store to view details.": "选择 Vector Store 以查看详情。",
    "Create a vector store": "创建 Vector Store",
    "Vector stores allow Assistants to search information in your documents using the File Search tool.": "Vector Store 允许 Assistants 通过 File Search 工具搜索文档中的信息。",
    "Learn about vector stores": "了解 Vector Store",
    "Estimated usage": "预计用量",
    "so far this month": "本月截至目前",
    "Last active": "上次活动时间",
    "Expiration policy": "有效期规则",
    "Expires": "到期时间",
    "Files attached": "附加文件",
    "File": "文件",
    "Uploaded": "上传时间",
    "This vector store is empty.": "此 Vector Store 尚无文件。",
    "Used by": "使用者",
    "Create assistant": "创建 Assistant",
    "Search skills by name or ID...": "按名称或 ID 搜索 Skill…",
    "Select a skill to view details.": "选择 Skill 以查看详情。",
    "No skills found": "未找到 Skill",
    "Uploaded skills will appear here.": "已上传的 Skills 将在此处显示。",
    "Upload a skill": "上传 Skill",
    "Upload one folder per skill (must include SKILL.md), or upload a single zip bundle.": "每个 Skill 上传一个文件夹（必须包含 SKILL.md），或上传一个 ZIP 压缩包。",
    "Upload type": "上传方式",
    "Skill upload type": "Skill 上传方式",
    "Folder": "文件夹",
    "Upload a skill folder": "上传 Skill 文件夹",
    "Select one folder. We will bundle its contents as a skill.": "选择一个文件夹，系统会将其内容打包为 Skill。",
    "Select folder": "选择文件夹",
    "Upload a zip or drag your file here": "上传 ZIP 文件或将文件拖到这里",
    "Upload plugin": "上传插件",
    "Build a plugin": "构建插件",
    "Submit a plugin": "提交插件",
    "Build a plugin with reusable skills and MCP integrations, then publish it to the ChatGPT plugin directory.": "构建包含可复用 Skills 和 MCP 集成的插件，然后发布到 ChatGPT 插件目录。",
    "Create your plugin with Codex": "使用 Codex 创建插件",
    "Use the Plugin Creator to build a new plugin or adapt an existing one.": "使用 Plugin Creator 创建新插件或改造现有插件。",
    "Upload your plugin ZIP": "上传插件 ZIP 压缩包",
    "Review your package and upload the plugin zip.": "检查插件包并上传 ZIP 文件。",
    "Complete automated checks": "完成自动检查",
    "Review findings and resolve issues. Upload a revised ZIP for package changes, or update your MCP server and rescan.": "检查结果并解决问题。修改插件包后上传新的 ZIP，或更新 MCP 服务器后重新扫描。",
    "Submit for review": "提交审核",
    "Some submissions may need additional review from our team.": "部分提交可能需要团队进一步审核。",
    "Publish your plugin": "发布插件",
    "Once approved, publish when you’re ready.": "审核通过后，可在准备就绪时发布。",
    "Upload new or existing plugin": "上传新插件或现有插件",
    "Compress your plugin folder into a .zip file before uploading": "上传前请将插件文件夹压缩为 .zip 文件",
    "Complete identity verification": "完成身份验证",
    "You need a verified developer identity before you can create or upload a plugin.": "创建或上传插件前，需要完成开发者身份验证。",
    "Continue": "继续",
    "New evaluation": "新建评估",
    "Select your data source": "选择数据来源",
    "Choose how you’d like to provide test data for evaluation.": "选择为评估提供测试数据的方式。",
    "Import Logs": "导入日志",
    "Evaluate your stored Chat Completions and Responses.": "评估已存储的 Chat Completions 和 Responses。",
    "Create new data": "创建新数据",
    "Craft input data and prompts manually.": "手动编写输入数据和提示。",
    "Upload a file": "上传文件",
    "Upload responses or input data from a JSONL or CSV file.": "从 JSONL 或 CSV 文件上传响应或输入数据。",
    "Build a custom evaluation.": "构建自定义评估。",
    "Use the API": "使用 API",
    "Use the API for more control over your evaluation.": "通过 API 更灵活地控制评估。",
    "Your test cases will appear here": "测试用例将在此处显示",
    "Import a file with variables or test cases to preview them here.": "导入包含变量或测试用例的文件，在此处预览。",
    "Create test data": "创建测试数据",
    "Select example": "选择示例",
    "Edit the prompt and input variables to generate test data for your evaluation.": "编辑提示和输入变量，为评估生成测试数据。",
    "Run name": "运行名称",
    "Use {{curly braces}} to insert variables.": "使用 {{curly braces}} 插入变量。",
    "Message": "消息",
    "No models available": "暂无可用模型",
    "Add ground truth": "添加参考答案",
    "Data": "数据",
    "Add new row": "添加新行",
    "+ Add row": "+ 添加行",
    "Configure": "配置",
    "Classification": "分类",
    "Summarization": "摘要生成",
    "Import Chat Completions": "导入 Chat Completions",
    "Import Responses": "导入 Responses",
    "Import source": "导入来源",
    "Filter stored Chat Completions to import test data to your evaluation.": "筛选已存储的 Chat Completions，将测试数据导入评估。",
    "Filter logged Responses to import test data to your evaluation.": "筛选已记录的 Responses，将测试数据导入评估。",
    "Your logs data will appear here": "日志数据将在此处显示",
    "Set filters to preview logs data matching your criteria.": "设置筛选条件，预览符合条件的日志数据。",
    "You don't have Chat Completions stored in this project. Store completions by setting the": "此项目中尚未存储 Chat Completions。将 API 请求中的",
    "parameter in your API requests.": "参数设为相应值即可存储生成内容。",
    "Learn about storing Chat Completions": "了解如何存储 Chat Completions",
    "Import test data": "导入测试数据",
    "Import or upload a CSV or JSONL file with your test data.": "导入或上传包含测试数据的 CSV 或 JSONL 文件。",
    "Search by file name...": "按文件名称搜索…",
    "Create evaluation": "创建评估",
    "Test data": "测试数据",
    "Add test data from a JSONL or CSV file, or import your Logs.": "从 JSONL 或 CSV 文件添加测试数据，或导入日志。",
    "Import": "导入",
    "Runs": "运行记录",
    "Test criteria": "测试标准",
    "Choose what you want to evaluate — factuality, sentiment, and more.": "选择要评估的内容，例如事实准确性、情感倾向等。",
    "View all workflows": "查看所有工作流",
    "Preview mode": "预览模式",
    "Edit mode": "编辑模式",
    "Workflow actions": "工作流操作",
    "Get started with Agent Builder": "开始使用 Agent Builder",
    "Publish": "发布",
    "Get code": "获取代码",
    "Get code for your workflow.": "获取工作流的代码。",
    "Product for code generation": "代码生成目标产品",
    "Publish to get a workflow ID": "发布以获取工作流 ID",
    "To use ChatKit, you’ll need to publish this workflow to get a hosted workflow ID.": "使用 ChatKit 前，需要发布此工作流以获取托管工作流 ID。",
    "Quickstart": "快速入门",
    "Clone sample app": "克隆示例应用",
    "Color theme mode": "主题模式",
    "Profile": "个人资料",
    "The name associated with this account": "此账号关联的名称",
    "Email address": "邮箱地址",
    "The email address associated with this account": "此账号关联的邮箱地址",
    "Phone number": "电话号码",
    "The phone number associated with this account": "此账号关联的电话号码",
    "Default organization": "默认组织",
    "The organization used by default when making requests with your user API keys": "使用用户 API 密钥发起请求时默认使用的组织",
    "Revoke API key": "撤销 API 密钥",
    "View all keys": "查看所有密钥",
    "Multi-factor authentication": "多因素认证",
    "Enable MFA": "启用 MFA",
    "Log out of all devices": "退出所有设备",
    "Log out all": "全部退出登录",
    "Priority processing is now Fast mode": "Priority 处理现已更名为 Fast 模式",
    "Fast mode is the new name for Priority Processing in the API, matching /fast in Codex. It delivers up to 2.5x faster speeds with no change in intelligence.": "API 中的 Priority 处理现已更名为 Fast 模式，与 Codex 中的 /fast 对应。速度最高可提升至 2.5 倍，智能水平保持不变。",
    "Fast mode is the new name for Priority Processing in the API, matching /fast in Codex.": "API 中的 Priority 处理现已更名为 Fast 模式，与 Codex 中的 /fast 对应。",
    "It delivers up to 2.5x faster speeds with no change in intelligence.": "速度最高可提升至 2.5 倍，智能水平保持不变。",
    "Configure in settings": "在设置中配置",
    "Plays translated speech as it returns. Leave this off when you are not using headphones.": "翻译后的语音返回时即播放。未使用耳机时，请关闭此选项。",
    "Plays translated speech as it returns.": "翻译后的语音返回时即播放。",
    "Leave this off when you are not using headphones.": "未使用耳机时，请关闭此选项。",
    "Uses near-field input noise reduction for the next session.": "为下一次会话启用近场输入降噪。",
    "Navigation tabs": "导航选项卡",
    "Model usage": "模型使用权限",
    "Allow or block models": "允许或禁止使用模型",
    "Configure which models can be used in this project.": "配置此项目允许使用的模型。",
    "Select models": "选择模型",
    "Rate limits": "速率限制",
    "Set rate limits for models in this project. Rate limits are inherited from the organization unless overridden.": "设置此项目的模型速率限制。未单独设置时，将继承组织的限制。",
    "Other organization and system restrictions still apply. Changes may take time to apply to API requests.": "其他组织和系统限制仍然适用。修改可能需要一段时间才能对 API 请求生效。",
    "Loading model settings…": "正在加载模型设置…",
    "Model access": "模型访问权限",
    "Allow all models": "允许所有模型",
    "All current and future models are allowed.": "允许使用所有当前和未来的模型。",
    "Allow all except selected models": "允许除选中模型外的所有模型",
    "Block selected models. All other current and future models are allowed.": "禁止使用选中模型，允许其他所有当前和未来的模型。",
    "Allow only selected models": "仅允许选中模型",
    "All other current and future models are blocked.": "禁止使用其他所有当前和未来的模型。",
    "Search models": "搜索模型",
    "Model access after saving": "保存后的模型访问权限",
    "Allowed": "允许",
    "Blocked": "禁止",
    "Tokens / min (TPM)": "每分钟 Token 数（TPM）",
    "Request and other limits": "请求及其他限制",
    "Shared limits:": "共享限制：",
    "Live Audio rate limits": "Live 音频速率限制",
    "Max concurrent sessions": "最大并发会话数",
    "images per minute": "每分钟图像数",
    "Video": "视频",
    "Search members...": "搜索成员…",
    "Member type filter": "成员类型筛选",
    "Service accounts": "服务账号",
    "Service Account": "服务账号",
    "Organization Owner": "组织所有者",
    "Leave": "退出",
    "Select a member to view details.": "选择成员以查看详情。",
    "Add member": "添加成员",
    "Add project member": "添加项目成员",
    "Add member method": "添加成员的方式",
    "Select user": "选择用户",
    "Enter user email": "输入用户邮箱",
    "Select a user": "选择用户",
    "Member": "成员",
    "Owner": "所有者",
    "Viewer": "查看者",
    "Reader": "只读成员",
    "Full control: can manage project settings and members.": "拥有全部权限，可管理项目设置和成员。",
    "Can read/write data. No direct member-management controls.": "可读写数据，无直接管理成员的权限。",
    "Search groups...": "搜索组…",
    "Add group": "添加组",
    "No groups found": "未找到组",
    "Add an organization group to grant the group's members access to this project": "添加组织中的组，以授予组内成员此项目的访问权限",
    "Add groups to project": "为项目添加组",
    "Add groups": "添加组",
    "Search roles...": "搜索角色…",
    "Create role": "创建角色",
    "Preset": "预设",
    "Assignments": "角色分配",
    "Viewer role for project": "项目查看者角色",
    "Promptfoo Administrator": "Promptfoo 管理员",
    "Promptfoo Viewer": "Promptfoo 查看者",
    "Full Promptfoo access in the project": "拥有项目中 Promptfoo 的全部访问权限",
    "View Promptfoo evaluations, issues, and reports in the project": "查看项目中的 Promptfoo 评估、问题和报告",
    "Role name": "角色名称",
    "Describe this role (optional)": "描述此角色（可选）",
    "No webhook endpoints found": "未找到 Webhook 端点",
    "Create a webhook endpoint to receive events from OpenAI.": "创建 Webhook 端点以接收 OpenAI 事件。",
    "Create webhook endpoint": "创建 Webhook 端点",
    "The URL that OpenAI will POST webhook events to.": "OpenAI 通过 POST 发送 Webhook 事件的 URL。",
    "Event types": "事件类型",
    "API events that your endpoint is subscribed to.": "此端点订阅的 API 事件。",
    "Select event types...": "选择事件类型…",
    "Background Responses": "后台 Responses",
    "Eval Runs": "评估运行",
    "Videos": "视频",
    "Other": "其他",
    "Custom model providers": "自定义模型提供商",
    "Enable custom third-party providers in": "在",
    "Organization general settings": "组织常规设置",
    "to manage configured providers for evaluations.": "中启用自定义第三方提供商，以管理评估使用的提供商。",
    "Details": "详细信息",
    "Organization name": "组织名称",
    "Human-friendly label for your organization, shown in user interfaces": "组织在用户界面中显示的易读名称",
    "Organization ID": "组织 ID",
    "Identifier for this organization sometimes used in API requests": "此组织的标识符，部分 API 请求会使用它",
    "Verifications": "身份验证",
    "Verify as an individual or business to access protected models and submit ChatGPT apps": "完成个人或企业验证，以使用受保护的模型并提交 ChatGPT 应用",
    "Individual": "个人",
    "You are verifying as a solo developer.": "以独立开发者身份进行验证。",
    "Business": "企业",
    "You are verifying a registered company.": "以注册企业身份进行验证。",
    "Start": "开始",
    "Allow eval runs to use third-party models you configure under": "允许评估运行使用你在",
    "Enable custom providers for evals (datasets not supported)": "为评估启用自定义提供商（不支持数据集）",
    "Make OpenRouter models available for evaluation runs.": "允许评估运行使用 OpenRouter 模型。",
    "Enable OpenRouter models for datasets and evals": "为数据集和评估启用 OpenRouter 模型",
    "Create new Admin key": "创建新的管理员密钥",
    "Create new admin key": "创建新的管理员密钥",
    "Create admin key": "创建管理员密钥",
    "Use Admin keys for programmatic administration of your account. Admin keys grant access to endpoints detailed in the": "使用管理员密钥通过程序管理账号。管理员密钥可访问以下文档中列出的端点：",
    "API Reference for Organizations": "组织管理 API 参考",
    ". You also need Admin keys to access audit logs if you have enabled them in": "。访问审计日志也需要管理员密钥；可在以下页面启用审计日志：",
    "General Settings": "常规设置",
    "Create an Admin key to administer your account": "创建管理员密钥以管理账号",
    "Select...": "选择…",
    "People & Permissions": "成员与权限",
    "Invitations": "邀请",
    "Invite team members": "邀请团队成员",
    "Emails": "邮箱地址",
    "Invite to projects": "邀请加入项目",
    "All selected": "已全选",
    "Invite": "邀请",
    "Can modify billing information and manage organization members": "可修改账单信息并管理组织成员",
    "Can make standard API requests and read basic organizational data": "可发起标准 API 请求并读取组织基本数据",
    "Search invites...": "搜索邀请…",
    "No invites found": "未找到邀请",
    "Create group": "创建组",
    "Group name": "组名称",
    "No groups found in your organization": "组织中未找到组",
    "RESIDENCY": "数据驻留",
    "Overview": "概览",
    "Payment methods": "付款方式",
    "Billing history": "账单历史",
    "Credit grants": "赠送额度",
    "Credit Grants": "赠送额度",
    "Preferences": "偏好设置",
    "Promotions": "优惠活动",
    "Free trial": "免费试用",
    "API credits are separate from ChatGPT.": "API 额度与 ChatGPT 单独计费。",
    "Manage your subscription": "管理订阅",
    "Add payment details": "添加付款信息",
    "View usage": "查看用量",
    "Add or change payment method": "添加或更改付款方式",
    "View past and current invoices": "查看历史和当前账单",
    "Manage billing information": "管理账单信息",
    "Usage limits": "用量限额",
    "Set monthly budgets": "设置月度预算",
    "Pricing": "价格",
    "View pricing and FAQs": "查看价格和常见问题",
    "You have not started a billing plan yet": "你尚未开通计费计划",
    "To add a payment method and start paying for API usage, go to the": "要添加付款方式并为 API 用量付费，请前往",
    "Billing overview": "账单概览",
    "page and select \"Add payment details\" to continue.": "页面，并选择“添加付款信息”以继续。",
    "No invoices found": "未找到账单",
    "Previous invoices page": "上一页账单",
    "Next invoices page": "下一页账单",
    "No credit grants found.": "未找到赠送额度。",
    "Changes to these preferences will apply to future invoices only. If you need a past invoice reissued, please contact ar@openai.com.": "这些偏好设置仅适用于之后的账单。如需重新开具历史账单，请联系 ar@openai.com。",
    "Company name": "公司名称",
    "If specified, this name will appear on invoices instead of your organization name.": "如已填写，账单将显示此名称，而非组织名称。",
    "Purchase order (PO) number": "采购订单（PO）编号",
    "Your PO number will be displayed on future invoices.": "之后的账单将显示此 PO 编号。",
    "Billing email": "账单邮箱",
    "Invoices and other billing notifications will be sent here (in addition to being sent to the owners of your organization).": "账单及相关通知将发送至此邮箱，同时也会发送给组织所有者。",
    "Primary business address": "主要营业地址",
    "This is the physical address of the company purchasing OpenAI services and is used to calculate any applicable sales tax.": "购买 OpenAI 服务的公司所在地地址，用于计算适用的销售税。",
    "Address line 1": "地址第 1 行",
    "Address line 2": "地址第 2 行",
    "Postal code": "邮政编码",
    "State, county, province, or region": "州、县、省或地区",
    "Business tax ID": "企业税号",
    "If you are a business tax registrant, please enter your business tax ID here.": "如果企业已进行税务登记，请在此输入企业税号。",
    "Add a promotional credit": "添加优惠额度",
    "Enter a promotional code to receive credits on your account.": "输入优惠码，为账号领取额度。",
    "Promotional code": "优惠码",
    "Enter code": "输入优惠码",
    "Apply": "应用",
    "Applied promotions": "已使用的优惠",
    "You haven't applied any promotions yet": "你尚未使用优惠",
    "Applied promotions will appear here": "已使用的优惠将在此处显示",
    "Usage Tiers": "用量等级",
    "Unlock higher API rate limits as your organization purchases more credits. Your usage tier upgrades automatically when your total credit purchases reach each threshold.": "组织购买更多额度后，可解锁更高的 API 速率限制。累计购买额度达到相应门槛时，用量等级会自动提升。",
    "Upgrade tier": "提升等级",
    "Free progress": "免费等级进度",
    "Free tier": "免费等级",
    "Free tier (your tier)": "免费等级（当前等级）",
    "Contact our sales team to learn more about custom rate limits.": "联系销售团队，了解自定义速率限制。",
    "Contact sales": "联系销售",
    "API usage is subject to rate limits applied on tokens per minute (TPM), requests per minute or day (RPM/RPD), and other model-specific limits. Your organization's rate limits are listed below.": "API 用量受每分钟 Token 数（TPM）、每分钟或每天请求数（RPM/RPD）及其他模型限制约束。下方列出了组织的速率限制。",
    "Visit our": "查看",
    "rate limits guide": "速率限制指南",
    "to learn more about how rate limits work.": "，了解速率限制的工作方式。",
    "Models in use": "正在使用的模型",
    "Rate limits tier": "速率限制等级",
    "Token limits": "Token 限制",
    "Batch queue limits": "批处理队列限制",
    "Latest models": "最新模型",
    "View all models": "查看所有模型",
    "Read docs": "阅读文档",
    "Download tunnel-client": "下载 tunnel-client",
    "Create tunnel": "创建隧道",
    "No tunnels yet": "暂无隧道",
    "Create your first tunnel to connect MCP servers behind a firewall.": "创建首个隧道，连接防火墙后的 MCP 服务器。",
    "e.g. West Coast MCP tunnel": "例如：西海岸 MCP 隧道",
    "Add a short description to help your team.": "添加简短说明，方便团队了解用途。",
    "Required. Add a short description to help your team.": "必填。添加简短说明，方便团队了解用途。",
    "Organizations": "组织",
    "Select one or more organizations, or search for an exact organization ID.": "选择一个或多个组织，或使用完整组织 ID 搜索。",
    "ChatGPT workspaces": "ChatGPT 工作空间",
    "Search workspaces by name or ID": "按名称或 ID 搜索工作空间",
    "Select ChatGPT workspaces, or search for an exact workspace ID.": "选择 ChatGPT 工作空间，或使用完整工作空间 ID 搜索。",
    "All systems operational": "所有系统运行正常",
    "All projects": "所有项目",
    "Pause live updates": "暂停实时更新",
    "Resume live updates": "恢复实时更新",
    "Personal uptime": "你的服务可用率",
    "API incident history": "API 事故历史",
    "Elevated latency for some API requests": "部分 API 请求延迟升高",
    "This incident has been resolved.": "此事故已解决。",
    "Elevated errors across ChatGPT, Codex, and the API including the Agents API": "ChatGPT、Codex 及 API（包括 Agents API）的错误率升高",
    "We are seeing elevated error rates across API models": "API 模型的错误率升高",
    "Elevated errors with gpt-image-2.5-flare": "gpt-image-2.5-flare 的错误率升高",
    "Elevated errors for GPT-5.6 Sol on the API": "API 中 GPT-5.6 Sol 的错误率升高",
    "Show more": "显示更多",
    "Visibility": "可见性",
    "Sharing": "共享",
    "Usage dashboard": "用量仪表板",
    "Usage dashboard shows activity and costs for your organization.": "用量仪表板显示组织的活动和费用。",
    "Visibility settings for the Usage dashboard": "用量仪表板可见性设置",
    "Visible to organization owners and users with usage dashboard permissions": "对组织所有者及拥有用量仪表板权限的用户可见",
    "Visible to everyone": "对所有成员可见",
    "Logs page": "日志页面",
    "Controls who can see Logs in the dashboard UI. This does not change API access to Responses, stored Chat Completions, or Traces.": "控制仪表板中日志页面的可见范围。此设置不会改变 Responses、已存储的 Chat Completions 或 Traces 的 API 访问权限。",
    "Visibility settings for the Logs page": "日志页面可见性设置",
    "Hidden": "隐藏",
    "Visible to organization owners": "对组织所有者可见",
    "Control which hosted tools are enabled in the Responses API.": "控制 Responses API 中启用的托管工具。",
    "MCP tool usage": "MCP 工具使用权限",
    "Enable MCP tools for all members of your organization.": "为组织的所有成员启用 MCP 工具。",
    "Settings for MCP tool usage": "MCP 工具使用权限设置",
    "Enabled for all projects": "为所有项目启用",
    "Enabled for selected projects": "为选中项目启用",
    "Web search tool usage": "Web search 工具使用权限",
    "Enable the web search tool for all members of your organization.": "为组织的所有成员启用 Web search 工具。",
    "Settings for Web search tool usage": "Web search 工具使用权限设置",
    "File search tool usage": "File search 工具使用权限",
    "Enable the file search tool for all members of your organization.": "为组织的所有成员启用 File search 工具。",
    "Settings for File search tool usage": "File search 工具使用权限设置",
    "Image generation tool usage": "Image generation 工具使用权限",
    "Enable the image generation tool for all members of your organization.": "为组织的所有成员启用 Image generation 工具。",
    "Settings for Image generation tool usage": "Image generation 工具使用权限设置",
    "Code interpreter tool usage": "Code interpreter 工具使用权限",
    "Enable the code interpreter tools for all members of your organization.": "为组织的所有成员启用 Code interpreter 工具。",
    "Settings for Code interpreter tool usage": "Code interpreter 工具使用权限设置",
    "Container network mode": "容器网络模式",
    "ELEVATED RISK": "高风险",
    "Configure outbound network access for container-based tools.": "配置容器工具的外部网络访问权限。",
    "Enable sharing of model feedback from the Platform": "允许共享平台中的模型反馈",
    "Enable all members of your organization to share feedback and chats with OpenAI to help improve and train our models. If enabled, users can click the “thumbs down” button on model responses in the Playground and choose to share their feedback and content from the current chat.": "允许组织成员向 OpenAI 共享反馈和对话，以帮助改进和训练模型。启用后，用户可点击 Playground 中模型响应的“点踩”按钮，并选择共享反馈及当前对话内容。",
    "Settings for feedback collection in the Playground": "Playground 反馈收集设置",
    "Share evaluation and fine-tuning data with OpenAI": "与 OpenAI 共享评估和微调数据",
    "Turn on sharing with OpenAI for all evaluation and fine-tuning data from your organization, including evaluation and fine tuning prompts, completions, grading logic, and results, to improve and train our models. Only evaluation and fine-tuning data created after turning this setting on will be shared. You can change your settings at any time to disable sharing evaluation and fine-tuning data.": "与 OpenAI 共享组织的评估和微调数据，包括提示、生成内容、评分逻辑和结果，以改进和训练模型。仅共享启用后创建的评估和微调数据。你可随时修改设置以停止共享。",
    "Settings for sharing evaluation and fine-tuning data with OpenAI": "与 OpenAI 共享评估和微调数据的设置",
    "Share inputs and outputs with OpenAI": "与 OpenAI 共享输入和输出",
    "Turn on sharing with OpenAI for inputs and outputs from your organization to help us develop and improve our services, including for improving and training our models. Only traffic sent after turning this setting on will be shared. You can change your settings at any time to disable sharing inputs and outputs.": "与 OpenAI 共享组织的输入和输出，以帮助开发和改进服务，包括改进和训练模型。仅共享启用后发送的数据。你可随时修改设置以停止共享输入和输出。",
    "Settings for sharing API data with OpenAI": "与 OpenAI 共享 API 数据的设置",
    "Audit logging": "审计日志",
    "Enable logging of user actions and configuration changes within this organization for compliance and security analysis. Once enabled, it cannot be disabled without contacting OpenAI.": "记录组织中的用户操作和配置变更，用于合规与安全分析。启用后，需联系 OpenAI 才能关闭。",
    "Enable audit logging": "启用审计日志",
    "API call logging": "API 调用日志",
    "Choose how your organization logs data from supported API calls, including chat completions, voice interactions, and other processed outputs. Logged data is accessible within your organization for review, analysis, and evaluation purposes.": "选择组织如何记录支持的 API 调用数据，包括 Chat Completions、语音交互及其他处理结果。组织内可访问这些日志，用于检查、分析和评估。",
    "Note: API calls from the Responses API are logged by default. Use the `store=false` API parameter to disable logging.": "注意：Responses API 调用默认记录日志。使用 API 参数 `store=false` 可关闭日志记录。",
    "Setting for API call logging": "API 调用日志设置",
    "Enabled per call": "按每次调用启用",
    "No workload identity provider": "暂无 Workload Identity Provider",
    "Create a workload identity provider to manage external workload identities.": "创建 Workload Identity Provider，以管理外部工作负载身份。",
    "Create identity provider": "创建身份提供商",
    "Create workload identity provider": "创建 Workload Identity Provider",
    "Enter the settings for your workload identity provider.": "输入 Workload Identity Provider 的设置。",
    "e.g. Azure Production": "例如：Azure 生产环境",
    "Provider type": "提供商类型",
    "OIDC Issuer URL": "OIDC 发行者 URL",
    "Audience": "受众",
    "Describe the provider": "描述提供商",
    "Advanced": "高级设置",
    "Configure custom OIDC discovery, uploaded JWKS, and derived attributes for providers that cannot use standard discovery metadata or raw token claims directly.": "为无法直接使用标准发现元数据或原始 Token 声明的提供商，配置自定义 OIDC 发现、上传的 JWKS 和派生属性。",
    "Use custom URL for OIDC discovery": "使用自定义 URL 进行 OIDC 发现",
    "Use uploaded JWKS for token verification": "使用上传的 JWKS 验证 Token",
    "Custom OIDC discovery URL": "自定义 OIDC 发现 URL",
    "Attribute transformations": "属性转换",
    "CEL expressions can derive OpenAI attributes from token claims under assertion. The openai. prefix is applied automatically.": "CEL 表达式可从 assertion 中的 Token 声明派生 OpenAI 属性，系统会自动添加 openai. 前缀。",
    "IP allowlist": "IP 允许列表",
    "IP allowlists": "IP 允许列表",
    "Domain allowlist": "域名允许列表",
    "Restrict API access to the IP addresses or CIDR ranges you specify. Changes may take up to 15 minutes to take effect. You can create up to": "将 API 访问限制为指定 IP 地址或 CIDR 范围。修改最多需要 15 分钟生效。组织最多可创建",
    "allowlists for your organization. Each allowlist can include up to": "个允许列表。每个允许列表最多可包含",
    "IP addresses or CIDR ranges. Project-level coverage overrides organization-level coverage.": "个 IP 地址或 CIDR 范围。项目级规则会覆盖组织级规则。",
    "Create allowlist": "创建允许列表",
    "No IP allowlists": "暂无 IP 允许列表",
    "Create an IP allowlist before covering your organization or projects.": "请先创建 IP 允许列表，再将其应用于组织或项目。",
    "mTLS adds an extra layer of security by requiring client certificates for API requests. Upload and manage your organization's certificates to authenticate requests, ensuring only authorized clients can access your API.": "mTLS 要求 API 请求提供客户端证书，以增加安全保护。上传并管理组织证书来验证请求，确保只有获授权的客户端能够访问 API。",
    "Upload a certificate, then activate it to enforce mutual TLS.": "上传并激活证书，以强制使用 mTLS。",
    "Test certificates": "测试证书",
    "Add domains to generate a public key": "添加域名以生成公钥",
    "Generate a public key to use ChatKit on specified domains.": "生成公钥，以在指定域名上使用 ChatKit。",
    "Add domains": "添加域名",
    "Add allowed domains": "添加允许的域名",
    "Generate a public key for use on the specified domains.": "生成可在指定域名上使用的公钥。",
    "Generate key": "生成密钥",
    "Create IP allowlist": "创建 IP 允许列表",
    "Configure the IP ranges for this allowlist, validate an IP against the draft ranges, and manage coverage for each scope.": "配置允许列表的 IP 范围，验证 IP 是否符合草稿规则，并管理各个范围的适用规则。",
    "Office network": "办公网络",
    "Allowed IP ranges": "允许的 IP 范围",
    "Add IP addresses or CIDR ranges that can access the API with API keys.": "添加允许使用 API 密钥访问 API 的 IP 地址或 CIDR 范围。",
    "No IP addresses configured": "尚未配置 IP 地址",
    "If this allowlist covers a scope, all public traffic for that scope will be blocked.": "如果此允许列表已应用于某个范围，该范围的所有公网流量都将被阻止。",
    "Add IP address or CIDR range": "添加 IP 地址或 CIDR 范围",
    "Validate an IP": "验证 IP 地址",
    "Check": "检查",
    "Upload a certificate": "上传证书",
    "Upload a chain of one or more X.509 certificates to authenticate API requests. Certificates must be signed by the bottom-most intermediate certificate, and have the": "上传包含一个或多个 X.509 证书的证书链，以验证 API 请求。证书必须由最底层中间证书签名，并包含",
    "extension.": "扩展。",
    "Empty name": "名称为空",
    "Certificate filters": "证书筛选条件",
    "Optional CEL expression": "可选的 CEL 表达式",
    "Certificate": "证书",
    "Upload certificate": "上传证书",
    "Dashboard": "仪表板",
    "Developer Docs": "开发者文档",
    "Learn about language model tokenization": "了解语言模型如何划分 Token",
    "OpenAI's large language models process text using": "OpenAI 的大型语言模型使用",
    ", which are common sequences of characters found in a set of text. The models learn to understand the statistical relationships between these tokens, and excel at producing the next token in a sequence of tokens.": "处理文本。Token 是文本中常见的字符序列。模型学习这些 Token 之间的统计关系，并生成序列中的下一个 Token。",
    "You can use the tool below to understand how a piece of text might be tokenized by a language model, and the total count of tokens in that piece of text.": "使用下方工具了解模型如何将文本划分为 Token，以及文本的 Token 总数。",
    "Enter some text": "输入文本",
    "Show example": "显示示例",
    "Characters": "字符数",
    "View options": "显示选项",
    "A helpful rule of thumb is that one token generally corresponds to ~4 characters of text for common English text. This translates to roughly ¾ of a word (so 100 tokens ~= 75 words).": "对于常见英文文本，一个 Token 通常约等于 4 个字符，或约四分之三个单词（因此 100 个 Token 约等于 75 个单词）。",
    "If you need a programmatic interface for tokenizing text, check out our": "如需通过程序划分 Token，可使用我们的",
    "package for Python. For JavaScript, the community-supported": "Python 软件包。对于 JavaScript，可使用社区维护的",
    "package works with most GPT models.": "软件包，适用于大多数 GPT 模型。",
    "Evals will be removed on November 30, 2026. For new workflows, we recommend using Promptfoo.": "Evals 将于 2026 年 11 月 30 日移除。新的工作流程建议使用 Promptfoo。",
    "Evaluation": "评估",
    "Evaluations": "评估",
    "Select datasets or evals": "选择数据集或评估",
    "Your datasets will appear here": "数据集将在此处显示",
    "Create a dataset to label, annotate, and evaluate your data.": "创建数据集以标记、注释和评估数据。",
    "Search...": "搜索…",
    "You'll need to set up billing before you can create evaluations": "创建评估前，请先设置账单信息",
    "Confirm deletion of vector store": "确认删除 Vector Store",
    "Are you sure you would like to delete the vector store": "确定要删除以下 Vector Store 吗：",
    "Delete vector store": "删除 Vector Store",
    "tokens": "Token",
    "GPT-4 & GPT-3.5 (legacy)": "GPT-4 & GPT-3.5（旧版）",
    "GPT-3 (legacy)": "GPT-3（旧版）",
    "Controls the service_tier param for requests with non-specified or auto service tier. If the model doesn't support the selected tier, it will fallback to default.": "控制 API 请求未指定 service_tier 或设为 auto 时采用的服务等级。若模型不支持所选服务等级，则回退到默认值。",
    "Choose which service tiers users can specify in this project’s API requests. Requests using disabled tiers will be rejected.": "选择用户可在此项目的 API 请求中指定的服务等级。使用已禁用的服务等级发送请求将被拒绝。",
    "Project Default Service Tier": "项目默认服务等级",
    "Allowed non-standard service tiers": "允许的非标准服务等级",
    "Service Tier": "服务等级",
    "Sends traffic to Standard processing (pay-as-you-go)": "将请求发送至标准处理服务（按量付费）",
    "Sends traffic to Fast processing (pay-as-you-go, subject to an auto ramp-up period, previously Priority)": "将请求发送至 Fast 处理服务（按量付费，需经过自动逐步提升流量的阶段，原称 Priority）",
    "No members found": "未找到成员",
    "No members found for the selected filter": "未找到符合所选筛选条件的成员",
    "You have permission to view and manage all API keys in this project.": "你有权限查看和管理此项目中的所有 API 密钥。",
    "Do not share your API key with others or expose it in the browser or other client-side code.": "请勿与他人分享你的 API 密钥，也不要将其暴露在浏览器或其他客户端代码中。",
    "To protect your account's security, OpenAI may automatically disable any API key that has leaked publicly.": "为保护你的账户安全，OpenAI 可能会自动禁用已公开泄露的 API 密钥。",
    "To protect your account’s security, OpenAI may automatically disable any API key that has leaked publicly.": "为保护你的账户安全，OpenAI 可能会自动禁用已公开泄露的 API 密钥。",
    "You have permission to view and manage all API keys in this project. Do not share your API key with others or expose it in the browser or other client-side code. To protect your account's security, OpenAI may automatically disable any API key that has leaked publicly.": "你有权限查看和管理此项目中的所有 API 密钥。请勿与他人分享你的 API 密钥，也不要将其暴露在浏览器或其他客户端代码中。为保护你的账户安全，OpenAI 可能会自动禁用已公开泄露的 API 密钥。",
    "You have permission to view and manage all API keys in this project. Do not share your API key with others or expose it in the browser or other client-side code. To protect your account’s security, OpenAI may automatically disable any API key that has leaked publicly.": "你有权限查看和管理此项目中的所有 API 密钥。请勿与他人分享你的 API 密钥，也不要将其暴露在浏览器或其他客户端代码中。为保护你的账户安全，OpenAI 可能会自动禁用已公开泄露的 API 密钥。"
  });
  // END GENERATED TRANSLATIONS

  // 界面提示与页面数据使用不同规则；所有规则都随单文件脚本发布。
  const CONFIG = Object.freeze({
    origin: "https://platform.openai.com",
    attributes: ["aria-label", "title", "placeholder", "alt", "data-placeholder"],
    contentSelector: "script, style, noscript, pre, code, textarea, input, [contenteditable]:not([contenteditable='false']), [role='code'], [role='textbox'], [data-code], .cm-editor, .monaco-editor, [data-message-author-role], [data-message-content], [data-user-content], .prose, .markdown, .markdown-body, .tokenizer-tkn",
    ignoredSelector: "[translate='no'], [data-openai-translate='ignore']",
    resourceSelector: "[data-resource-name], [data-resource-id], [data-project-id], [data-organization-id], [data-secret-value]",
    resourceColumns: new Set([
      "name", "agent name", "template name", "project name", "file name", "filename", "role name",
      "secret", "secret key", "secret value", "description", "message", "input", "output", "value",
      "名称", "agent 名称", "模板名称", "项目名称", "文件名称", "角色名称", "密钥", "密钥值", "说明", "消息", "输入", "输出", "值"
    ]),
    resourcePath: /\/(?:prompts\/pmpt_|agents\/agent_|(?:files\/file[-_])|(?:vector[_-]stores\/vs_)|skills\/skill_|projects\/proj_)[^/]+(?:\/|$)/,
    resourceDetailPath: /\/(?:prompts\/pmpt_|agents\/agent_|(?:files\/file[-_])|(?:vector[_-]stores\/vs_)|skills\/skill_|projects\/proj_)[^/]+\/?$/,
    resourceControlLabel: /^(?:(?:select|choose|switch|current|active|search|filter|attach)(?: an?| your| existing)?\s+)?(?:projects?|organizations?|agents?|environment templates?|vector stores?|prompts?|files?|skills?|secrets?|datasets?|templates?|models?|tools?|voices?|(?:mcp\s+)?servers?)(?:\s+(?:selector|switcher|selection))?(?:\.\.\.|…)?$|^(?:(?:选择|切换|当前|筛选|搜索|关联|添加|附加)(?:一个|你的|的|现有)?\s*)?(?:项目|组织|Agent|环境模板|Vector Store|Prompt|文件|Skill|密钥|数据集|模板|模型|工具|语音|(?:MCP\s*)?服务器)(?:选择器)?(?:…)?$/i
  });
  const ATTRIBUTES = CONFIG.attributes;
  const RESOURCE_MENU_ACTIONS = new Set([
    "Create project", "Create a new project", "Manage projects", "Organization settings", "Profile settings",
    "Create environment template", "Create agent", "New agent", "Create vector store", "Create a vector store",
    "New prompt", "Upload file", "Upload skill", "Upload a skill", "Create secret", "Create dataset"
  ].flatMap((value) => [value, TEXT[value]]).filter(Boolean));
  const protectionContext = {
    controls: new Set(),
    popups: new Set(),
    tableHeaders: new WeakMap()
  };
  const dateUnits = {
    second: "秒",
    minute: "分钟",
    hour: "小时",
    day: "天",
    week: "周",
    month: "个月",
    year: "年"
  };
  const months = {
    Jan: "1 月", Feb: "2 月", Mar: "3 月", Apr: "4 月", May: "5 月", Jun: "6 月",
    Jul: "7 月", Aug: "8 月", Sep: "9 月", Oct: "10 月", Nov: "11 月", Dec: "12 月"
  };
  const voices = [
    ["Ripple", "Warm and conversational", "English", "Australian influenced", "Male"],
    ["Vesper", "Clear and direct", "English", "British influenced", "Male"],
    ["Willow", "Expressive and bright", "English", "Irish influenced", "Female"],
    ["Stone", "Calm and precise", "English", "Irish influenced", "Male"],
    ["Meridian", "Grounded and measured", "English", "North American influenced", "Male"],
    ["Gleam", "Warm and conversational", "English", "North American influenced", "Female"],
    ["Bossa", "Clear and direct", "Portuguese", "Brazilian influenced", "Female"],
    ["Tempo", "Grounded and measured", "Portuguese", "Brazilian influenced", "Male"],
    ["Cedar", "Open and upbeat", "English", "North American influenced", "Male"],
    ["Marin", "Animated and earnest", "English", "North American influenced", "Female"],
    ["Quartz", "Warm and conversational", "English", "Australian influenced", "Female"],
    ["Alloy", "Balanced and clear", "English", "North American influenced", "Male"],
    ["Ash", "Savvy and relaxed", "English", "North American influenced", "Male"],
    ["Ballad", "Cheerful and candid", "English", "North American influenced", "Male"],
    ["Coral", "Easygoing and versatile", "English", "North American influenced", "Female"],
    ["Echo", "Bright and inquisitive", "English", "North American influenced", "Male"],
    ["Sage", "Confident and optimistic", "English", "North American influenced", "Female"],
    ["Shimmer", "Composed and direct", "English", "North American influenced", "Female"],
    ["Verse", "Calm and affirming", "English", "North American influenced", "Male"],
    ["Beacon", "Clear and personable", "English", "Filipino influenced", "Male"],
    ["Delta", "Warm and easygoing", "English", "Southern U.S. influenced", "Female"],
    ["Cinder", "Steady and grounded", "English", "Southern U.S. influenced", "Male"]
  ];

  function translate(value) {
    if (!value || !/[A-Za-z]/.test(value)) return null;
    if (Object.prototype.hasOwnProperty.call(TEXT, value)) return TEXT[value];
    const normalized = value.replace(/\s+/g, " ").trim();
    if (Object.prototype.hasOwnProperty.call(TEXT, normalized)) return TEXT[normalized];

    // 仅处理明确的界面格式；插入的名称、模型 ID 和技术单位原样保留。
    const results = normalized.match(/^([\d,]+) results?$/);
    if (results) return `${results[1]} 项结果`;
    const permissions = normalized.match(/^([\d,]+) selected permissions?$/);
    if (permissions) return `已选 ${permissions[1]} 项权限`;
    const rows = normalized.match(/^([\d,]+) rows?$/);
    if (rows) return `${rows[1]} 行`;
    const characters = normalized.match(/^(\d+)\s*\/\s*(\d+) characters$/);
    if (characters) return `${characters[1]}/${characters[2]} 个字符`;
    const step = normalized.match(/^Step (\d+)\s*(?:\/|of)\s*(\d+)$/);
    if (step) return `第 ${step[1]} 步，共 ${step[2]} 步`;
    const tier = normalized.match(/^Tier (\d+)( \(your tier\))?$/);
    if (tier) return `第 ${tier[1]} 级${tier[2] ? "（当前等级）" : ""}`;
    const servers = normalized.match(/^Recommended MCP servers:\s*(.+)$/);
    if (servers) return `推荐 MCP 服务器：${servers[1]}`;
    const details = normalized.match(/^View details for (.+)$/);
    if (details) return `查看 ${details[1]} 的详情`;
    const modelLimit = normalized.match(/^Edit ([\w.-]+) limit$/);
    if (modelLimit) return `编辑 ${modelLimit[1]} 的限制`;
    const storageHours = normalized.match(/^([\d.,]+)\s+(KB|MB|GB) hours$/);
    if (storageHours) return `${storageHours[1]} ${storageHours[2]}·小时`;
    const deletedStore = normalized.match(/^Vector store "([^"]+)" deleted$/);
    if (deletedStore) return `Vector Store "${deletedStore[1]}" 已删除`;

    for (const [name, trait, language, accent, gender] of voices) {
      if (normalized === `${name} ${trait} ${language} ${accent} ${gender}`) {
        return `${name} · ${TEXT[trait]} · ${TEXT[language]} · ${TEXT[accent]} · ${TEXT[gender]}`;
      }
    }

    const preview = normalized.match(/^Play ([\w-]+) preview$/i);
    if (preview) return `试听 ${preview[1]} 语音`;

    const relativeDate = normalized.match(/^(\d+)\s+(seconds?|minutes?|hours?|days?|weeks?|months?|years?)\s+ago$/i);
    if (relativeDate) {
      const unit = relativeDate[2].toLowerCase().replace(/s$/, "");
      return `${relativeDate[1]}${dateUnits[unit]}前`;
    }

    const shortDate = normalized.match(/^(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s+(\d{1,2})$/);
    if (shortDate) return `${months[shortDate[1]]}${Number(shortDate[2])} 日`;

    const monthSpend = normalized.match(/^(January|February|March|April|May|June|July|August|September|October|November|December) spend$/i);
    if (monthSpend) {
      const month = monthSpend[1][0].toUpperCase() + monthSpend[1].slice(1, 3).toLowerCase();
      return `${months[month]}支出`;
    }

    const cardAction = normalized.match(/^(.+?)\s+(top|bottom) action$/i);
    if (cardAction) {
      const subject = cardAction[1] === "Audio & Voice"
        ? "音频与语音"
        : cardAction[1] === "Image"
          ? "图像"
          : cardAction[1];
      const position = cardAction[2].toLowerCase() === "top" ? "上方" : "下方";
      return `${subject} ${position}操作`;
    }

    const updateLabel = normalized.match(/^Dismiss update:\s*(.+)$/i);
    if (updateLabel) return `关闭更新：${TEXT[updateLabel[1]] || updateLabel[1]}`;

    return null;
  }

  function isPlatformPage() {
    return location.origin === CONFIG.origin;
  }

  function elementFor(node) {
    return node?.nodeType === Node.ELEMENT_NODE ? node : node?.parentElement;
  }

  function normalizeLabel(value) {
    return (value || "").replace(/\s+/g, " ").trim();
  }

  function isResourceControl(element) {
    const labels = [element.getAttribute("aria-label"), element.getAttribute("title")];
    for (const id of (element.getAttribute("aria-labelledby") || "").split(/\s+/)) {
      if (id) labels.push(document.getElementById(id)?.textContent);
    }
    for (const label of element.labels || []) labels.push(label.textContent);
    // 没有辅助标签的默认项目切换器也必须保留其真实名称。
    if (normalizeLabel(element.textContent) === "Default project") return true;
    return labels.some((label) => CONFIG.resourceControlLabel.test(normalizeLabel(label)));
  }

  function refreshProtectionContext() {
    protectionContext.controls.clear();
    protectionContext.popups.clear();
    protectionContext.tableHeaders = new WeakMap();
    for (const control of document.querySelectorAll("[role='combobox'], [aria-haspopup='listbox'], [aria-haspopup='menu'], select")) {
      if (!isResourceControl(control)) continue;
      protectionContext.controls.add(control);
      for (const id of `${control.getAttribute("aria-controls") || ""} ${control.getAttribute("aria-owns") || ""}`.split(/\s+/)) {
        const popup = id && document.getElementById(id);
        if (popup) protectionContext.popups.add(popup);
      }
    }
    for (const popup of document.querySelectorAll("[role='listbox'], [role='menu']")) {
      for (const id of (popup.getAttribute("aria-labelledby") || "").split(/\s+/)) {
        if (id && protectionContext.controls.has(document.getElementById(id))) protectionContext.popups.add(popup);
      }
    }
  }

  function tableColumn(node) {
    const cell = elementFor(node)?.closest("td, [role='cell'], [role='gridcell']");
    const table = cell?.closest("table, [role='table'], [role='grid']");
    if (!table) return "";
    let headers = protectionContext.tableHeaders.get(table);
    if (!headers) {
      headers = [...table.querySelectorAll("thead th, [role='columnheader']")].filter((header) => header.closest("table, [role='table'], [role='grid']") === table);
      protectionContext.tableHeaders.set(table, headers);
    }
    const explicitIndex = Number(cell.getAttribute("aria-colindex"));
    const index = explicitIndex > 0 ? explicitIndex - 1 : typeof cell.cellIndex === "number"
      ? cell.cellIndex : [...cell.parentElement.children].filter((child) => child.matches("td, th, [role='cell'], [role='gridcell']")).indexOf(cell);
    return normalizeLabel(headers[index]?.textContent);
  }

  function isResourceElement(element) {
    if (element.closest(CONFIG.resourceSelector)) return true;
    if (CONFIG.resourceColumns.has(tableColumn(element).toLowerCase())) return true;
    const anchor = element.closest("a[href]");
    if (anchor) {
      try {
        const target = new URL(anchor.getAttribute("href"), location.href);
        if (target.origin === location.origin && CONFIG.resourcePath.test(target.pathname)) return true;
      } catch {
        // 非 URL 的 href 不参与资源识别。
      }
    }
    if (element.closest("h1") && CONFIG.resourceDetailPath.test(location.pathname)) return true;
    for (let ancestor = element; ancestor; ancestor = ancestor.parentElement) {
      if (protectionContext.controls.has(ancestor)) return true;
      if (protectionContext.popups.has(ancestor)) {
        // 保留搜索框和菜单操作，仅跳过实际资源选项。
        if (element.closest("[role='option'], option")) return true;
        const item = element.closest("[role='menuitem']");
        if (item && !RESOURCE_MENU_ACTIONS.has(normalizeLabel(item.textContent))) return true;
      }
    }
    return false;
  }

  function shouldSkip(node) {
    const element = elementFor(node);
    return !element || element.isContentEditable || Boolean(element.closest(`${CONFIG.contentSelector}, ${CONFIG.ignoredSelector}`)) || isResourceElement(element);
  }

  function translateInContext(value, node) {
    if (isResourceElement(elementFor(node))) return null;
    const column = tableColumn(node);
    if (value === "Never" && ["Last used", "LAST USED", "上次使用时间"].includes(column)) return "从未";
    if (value === "Default" && elementFor(node).closest("[role='radiogroup'], [role='radio']")) return "默认";
    return translate(value);
  }

  function translateTextNode(node) {
    if (node.nodeType !== Node.TEXT_NODE || shouldSkip(node)) return;
    const original = node.nodeValue;
    const leading = (original.match(/^\s*/) || [""])[0];
    const trailing = (original.match(/\s*$/) || [""])[0];
    const core = original.slice(leading.length, original.length - trailing.length);
    if (!core) return;
    const translated = translateInContext(core, node);
    if (translated !== null && translated !== core) node.nodeValue = `${leading}${translated}${trailing}`;
  }

  function translateElementAttributes(element) {
    if (element.closest(CONFIG.ignoredSelector)) return;
    const resourceProtected = isResourceElement(element);
    const contentProtected = shouldSkip(element);
    for (const attribute of ATTRIBUTES) {
      if (!element.hasAttribute(attribute)) continue;
      const original = element.getAttribute(attribute);
      const isControlHint = protectionContext.controls.has(element) && ["aria-label", "placeholder"].includes(attribute) && CONFIG.resourceControlLabel.test(normalizeLabel(original));
      if (resourceProtected && !isControlHint) continue;
      // 编辑器根节点的占位提示是 UI；编辑器内部属性和用户内容保持原样。
      const isInputHint = (element.matches("input, textarea, [contenteditable]:not([contenteditable='false']), [role='textbox'], .cm-editor[data-placeholder], .monaco-editor[data-placeholder]") && ["placeholder", "data-placeholder", "aria-label"].includes(attribute)) || (element.matches("input, textarea") && attribute === "title");
      if (contentProtected && !isControlHint && (!isInputHint || element.parentElement?.closest(`${CONFIG.contentSelector}, ${CONFIG.ignoredSelector}`))) continue;
      const translated = translate(original);
      if (translated !== null && translated !== original) element.setAttribute(attribute, translated);
    }
  }

  function translateTree(root) {
    if (!isPlatformPage() || !root) return;
    if (root.nodeType === Node.TEXT_NODE) {
      translateTextNode(root);
      return;
    }
    if (root.nodeType !== Node.ELEMENT_NODE) return;
    translateElementAttributes(root);
    if (shouldSkip(root)) return;
    const walker = document.createTreeWalker(root, NodeFilter.SHOW_ELEMENT | NodeFilter.SHOW_TEXT, {
      acceptNode(node) {
        if (node.nodeType === Node.ELEMENT_NODE && shouldSkip(node)) {
          translateElementAttributes(node);
          return NodeFilter.FILTER_REJECT;
        }
        return NodeFilter.FILTER_ACCEPT;
      }
    });
    let node;
    while ((node = walker.nextNode())) {
      if (node.nodeType === Node.TEXT_NODE) translateTextNode(node);
      else translateElementAttributes(node);
    }
  }

  function translateTitle() {
    if (!isPlatformPage()) return;
    const translated = translate(document.title);
    if (translated !== null && translated !== document.title) document.title = translated;
  }

  function start() {
    if (!isPlatformPage() || !document.body) return;
    refreshProtectionContext();
    translateTree(document.body);
    translateTitle();

    const pendingRoots = new Set();
    const pendingTextNodes = new Set();
    const pendingAttributeElements = new Set();
    let flushScheduled = false;

    function flushMutations() {
      flushScheduled = false;
      if (!isPlatformPage()) {
        pendingRoots.clear();
        pendingTextNodes.clear();
        pendingAttributeElements.clear();
        return;
      }

      const roots = [...pendingRoots];
      const textNodes = [...pendingTextNodes];
      const attributeElements = [...pendingAttributeElements];
      pendingRoots.clear();
      pendingTextNodes.clear();
      pendingAttributeElements.clear();

      refreshProtectionContext();

      const elementRoots = new Set(roots.filter((node) => node.nodeType === Node.ELEMENT_NODE));
      const coveredByAddedRoot = (node) => {
        let element = node.parentElement;
        while (element) {
          if (elementRoots.has(element)) return true;
          element = element.parentElement;
        }
        return false;
      };

      for (const root of roots) {
        if (!root.isConnected || coveredByAddedRoot(root)) continue;
        if (root.nodeType === Node.TEXT_NODE) translateTextNode(root);
        else if (root.nodeType === Node.ELEMENT_NODE) translateTree(root);
      }

      for (const node of textNodes) {
        if (node.isConnected && !coveredByAddedRoot(node)) translateTextNode(node);
      }
      for (const element of attributeElements) {
        if (element.isConnected && !coveredByAddedRoot(element)) translateElementAttributes(element);
      }
      translateTitle();
    }

    function scheduleMutationFlush() {
      if (flushScheduled) return;
      flushScheduled = true;
      requestAnimationFrame(flushMutations);
    }

    const observer = new MutationObserver((records) => {
      if (!isPlatformPage()) return;
      for (const record of records) {
        if (record.type === "characterData") {
          pendingTextNodes.add(record.target);
        } else if (record.type === "childList") {
          for (const node of record.addedNodes) {
            if (node.nodeType === Node.TEXT_NODE || node.nodeType === Node.ELEMENT_NODE) pendingRoots.add(node);
          }
        } else if (record.type === "attributes") {
          pendingAttributeElements.add(record.target);
        }
      }
      scheduleMutationFlush();
    });

    observer.observe(document.documentElement, {
      subtree: true,
      childList: true,
      characterData: true,
      attributes: true,
      attributeFilter: ATTRIBUTES
    });
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", start, { once: true });
  } else {
    start();
  }
})();
